require("ItemTweaker_Copy_ogsn");
-- OGSNTweakItem("Module.ItemName","AttributeName","New Attribute Value");

-- Some of these aren't necessary but I will do them all anyway
OGSNTweakItem("Base.Tshirt_DefaultTEXTURE","DisplayName","Plain T-Shirt");
OGSNTweakItem("Base.Tshirt_DefaultTEXTURE_TINT","DisplayName","Plain T-Shirt");
OGSNTweakItem("Base.Tshirt_WhiteTINT","DisplayName","Plain T-Shirt");
OGSNTweakItem("Base.Tshirt_WhiteLongSleeve","DisplayName","Plain Long Sleeve T-Shirt");
OGSNTweakItem("Base.Tshirt_WhiteLongSleeveTINT","DisplayName","Plain Long Sleeve T-Shirt");
OGSNTweakItem("Base.Tshirt_PoloStripedTINT","DisplayName","Striped T-Shirt");
OGSNTweakItem("Base.Tshirt_PoloTINT","DisplayName","Polo T-Shirt");
OGSNTweakItem("Base.Tshirt_DefaultDECAL","DisplayName","Random Decal T-Shirt");
OGSNTweakItem("Base.Tshirt_DefaultDECAL_TINT","DisplayName","Random Decal T-Shirt");
OGSNTweakItem("Base.Tshirt_SportDECAL","DisplayName","Random Decal - Sport T-Shirt");
OGSNTweakItem("Base.Tshirt_Rock","DisplayName","Rock T-Shirt");
OGSNTweakItem("Base.Tshirt_Sport","DisplayName","Sport T-Shirt");
OGSNTweakItem("Base.Tshirt_ArmyGreen","DisplayName","Army T-Shirt");
OGSNTweakItem("Base.Tshirt_CamoDesert","DisplayName","Army Camo Desert T-Shirt");
OGSNTweakItem("Base.Tshirt_CamoGreen","DisplayName","Army Camo Forest T-Shirt");
OGSNTweakItem("Base.Tshirt_CamoUrban","DisplayName","Army Camo Urban T-Shirt");
OGSNTweakItem("Base.Tshirt_Fossoil","DisplayName","Fossoil T-Shirt");
OGSNTweakItem("Base.Tshirt_Gas2Go","DisplayName","Gas2Go T-Shirt");
OGSNTweakItem("Base.Tshirt_McCoys","DisplayName","McCoys T-Shirt");
OGSNTweakItem("Base.Tshirt_PileOCrepe","DisplayName","PileOCrepe T-Shirt");
OGSNTweakItem("Base.Tshirt_PizzaWhirled","DisplayName","Pizza Whirled T-Shirt");
OGSNTweakItem("Base.Tshirt_BusinessSpiffo","DisplayName","Spiffo Business T-Shirt");
OGSNTweakItem("Base.Tshirt_SpiffoDECAL","DisplayName","Spiffo Decal T-Shirt");
OGSNTweakItem("Base.Tshirt_ThunderGas","DisplayName","ThunderGas T-Shirt");
OGSNTweakItem("Base.Tshirt_ValleyStation","DisplayName","Valley Station T-Shirt");
OGSNTweakItem("Base.Tshirt_IndieStoneDECAL","DisplayName","The Indie Stone T-Shirt");
OGSNTweakItem("Base.Tshirt_Profession_FiremanBlue","DisplayName","Fireman - Blue T-Shirt");
OGSNTweakItem("Base.Tshirt_Profession_FiremanRed02","DisplayName","Fireman - Dark Red T-Shirt");
OGSNTweakItem("Base.Tshirt_Profession_FiremanRed","DisplayName","Fireman - Light Red T-Shirt");
OGSNTweakItem("Base.Tshirt_Profession_FiremanWhite","DisplayName","Fireman - White T-Shirt");
OGSNTweakItem("Base.Tshirt_Scrubs","DisplayName","Medical T-Shirt");
OGSNTweakItem("Base.Tshirt_Ranger","DisplayName","Park Ranger T-Shirt");
OGSNTweakItem("Base.Tshirt_Profession_RangerBrown","DisplayName","Park Ranger - Brown T-Shirt");
OGSNTweakItem("Base.Tshirt_Profession_RangerGreen","DisplayName","Park Ranger - Green T-Shirt");
OGSNTweakItem("Base.Tshirt_Profession_PoliceBlue","DisplayName","Police - Blue T-Shirt");
OGSNTweakItem("Base.Tshirt_Profession_PoliceWhite","DisplayName","Police - White T-Shirt");
OGSNTweakItem("Base.Tshirt_PoliceGrey","DisplayName","Police - Deputy Grey T-Shirt");
OGSNTweakItem("Base.Tshirt_PoliceBlue","DisplayName","Police - Trooper Blue T-Shirt");
OGSNTweakItem("Base.Tshirt_Profession_VeterenGreen","DisplayName","Veteran - Green T-Shirt");
OGSNTweakItem("Base.Tshirt_Profession_VeterenRed","DisplayName","Veteran - Red T-Shirt");
