require("ItemTweaker_Copy_ogsn");
-- OGSNTweakItem("Module.ItemName","AttributeName","New Attribute Value");

-- Some of these aren't necessary but I will do them all anyway
OGSNTweakItem("Base.Shorts_ShortFormal","DisplayName","Shorts");
OGSNTweakItem("Base.Trousers_WhiteTEXTURE","DisplayName","Pants");
OGSNTweakItem("Base.Trousers_WhiteTINT","DisplayName","Pants");
OGSNTweakItem("Base.Trousers_Denim","DisplayName","Jeans");
OGSNTweakItem("Base.Trousers_JeanBaggy","DisplayName","Jeans - Baggy");
OGSNTweakItem("Base.TrousersMesh_DenimLight","DisplayName","Jeans - Denim");
OGSNTweakItem("Base.Trousers_ArmyService","DisplayName","Military Uniform - Army Dress");
OGSNTweakItem("Base.Trousers_CamoDesert","DisplayName","Military Uniform - Army Camo Desert");
OGSNTweakItem("Base.Trousers_CamoGreen","DisplayName","Military Uniform - Army Camo Forest");
OGSNTweakItem("Base.Trousers_CamoUrban","DisplayName","Military Uniform - Army Camo Urban");
OGSNTweakItem("Base.Trousers_NavyBlue","DisplayName","Military Uniform - Navy");
OGSNTweakItem("Base.Dungarees","DisplayName","Overalls");
OGSNTweakItem("Base.Trousers_Chef","DisplayName","Pants - Chef");
OGSNTweakItem("Base.Trousers_Fireman","DisplayName","Pants - Firefighter");
OGSNTweakItem("Base.Trousers_Ranger","DisplayName","Pants - Park Ranger");
OGSNTweakItem("Base.Trousers_PoliceGrey","DisplayName"," Pants - Police Deputy");
OGSNTweakItem("Base.Trousers_Police","DisplayName","Pants - Police Trooper");
OGSNTweakItem("Base.Trousers_PrisonGuard","DisplayName","Pants - Prison Guard");
OGSNTweakItem("Base.Trousers_Santa","DisplayName","Pants - Santa Suit Red");
OGSNTweakItem("Base.Trousers_SantaGReen","DisplayName","Pants - Santa Suit Green");
OGSNTweakItem("Base.Trousers_Scrubs","DisplayName","Pants - Medical Scrubs");
OGSNTweakItem("Base.Trousers_Suit","DisplayName","Pants - Suit");
OGSNTweakItem("Base.Trousers_SuitTEXTURE","DisplayName","Pants - Suit");
OGSNTweakItem("Base.Trousers_SuitWhite","DisplayName","Pants - Suit");
OGSNTweakItem("Base.Trousers_Padded","DisplayName","Pants - Winter");
OGSNTweakItem("Base.Shorts_CamoGreenLong","DisplayName","Shorts - Army Camo Forest");
OGSNTweakItem("Base.Shorts_CamoUrbanLong","DisplayName","Shorts - Army Camo Urban");
OGSNTweakItem("Base.Shorts_ShortDenim","DisplayName","Shorts - Denim");
OGSNTweakItem("Base.Shorts_LongDenim","DisplayName"," Shorts - Denim Long");
OGSNTweakItem("Base.Shorts_ShortSport","DisplayName","Shorts - Sport");
OGSNTweakItem("Base.Shorts_LongSport","DisplayName"," Shorts - Sport Long");
OGSNTweakItem("Base.Shorts_LongSport_Red","DisplayName"," Shorts - Sport Long Red");
OGSNTweakItem("Base.Trousers","DisplayName","Trousers");
OGSNTweakItem("Base.Trousers_Black","DisplayName","Trousers - Black");
