-- local ISMapSymbols_populateSymbolList = ISMapSymbols:populateSymbolList()
-- function ISMapSymbols:populateSymbolList()
--     table.insert(self.symbolList, "media/ui/LootableMaps/map_gun.png");
--     table.insert(self.symbolList, "media/ui/LootableMaps/map_hammer.png");
--     table.insert(self.symbolList, "media/ui/LootableMaps/map_medical.png");
--     table.insert(self.symbolList, "media/ui/LootableMaps/map_heart.png");
--     table.insert(self.symbolList, "media/ui/LootableMaps/map_square.png");
--     table.insert(self.symbolList, "media/ui/LootableMaps/map_checkmark.png");
--     table.insert(self.symbolList, "media/ui/LootableMaps/map_scribble.png");
--     table.insert(self.symbolList, "media/ui/LootableMaps/map_book.png");
--     table.insert(self.symbolList, "media/ui/LootableMaps/map_jewel.png");
--     table.insert(self.symbolList, "media/ui/LootableMaps/map_diamondshape.png");
--     table.insert(self.symbolList, "media/ui/LootableMaps/map_meat.png");
--     table.insert(self.symbolList, "media/ui/LootableMaps/map_carrot.png");



--     table.insert(self.symbolList, "media/ui/LootableMaps/map_arroweast.png");
--     table.insert(self.symbolList, "media/ui/LootableMaps/map_arrownorth.png");
--     table.insert(self.symbolList, "media/ui/LootableMaps/map_arrowsouth.png");
--     table.insert(self.symbolList, "media/ui/LootableMaps/map_arrowwest.png");
--     table.insert(self.symbolList, "media/ui/LootableMaps/map_exclamation.png");
--     table.insert(self.symbolList, "media/ui/LootableMaps/map_garbage.png");
--     table.insert(self.symbolList, "media/ui/LootableMaps/map_house.png");
--     table.insert(self.symbolList, "media/ui/LootableMaps/map_lock.png");
--     table.insert(self.symbolList, "media/ui/LootableMaps/map_o.png");
--     table.insert(self.symbolList, "media/ui/LootableMaps/map_skull.png");
--     table.insert(self.symbolList, "media/ui/LootableMaps/map_target.png");
--     table.insert(self.symbolList, "media/ui/LootableMaps/map_x.png");
--     table.insert(self.symbolList, "media/ui/LootableMaps/map_apple.png");
--     table.insert(self.symbolList, "media/ui/LootableMaps/map_lightning.png");
--     table.insert(self.symbolList, "media/ui/LootableMaps/map_question.png");
    -- table.insert(self.symbolList, "media/ui/LootableMaps/map_trap.png");
