require("ItemTweaker_Copy_ogsn");
local new_weight = "0.1"
OGSNTweakItem("spraypaint.SpraycanWhite","Weight",new_weight);
OGSNTweakItem("spraypaint.SpraycanRed","Weight",new_weight);
OGSNTweakItem("spraypaint.SpraycanBlue","Weight",new_weight);
OGSNTweakItem("spraypaint.SpraycanGreen","Weight",new_weight);
OGSNTweakItem("spraypaint.SpraycanOrange","Weight",new_weight);
OGSNTweakItem("spraypaint.SpraycanYellow","Weight",new_weight);
OGSNTweakItem("spraypaint.SpraycanViolet","Weight",new_weight);
OGSNTweakItem("spraypaint.SpraycanBlack","Weight",new_weight);
OGSNTweakItem("spraypaint.SpraycanCyan","Weight",new_weight);
OGSNTweakItem("spraypaint.ChalkWhite","Weight",new_weight);
OGSNTweakItem("spraypaint.ChalkRed","Weight",new_weight);
OGSNTweakItem("spraypaint.ChalkBlue","Weight",new_weight);
OGSNTweakItem("spraypaint.ChalkGreen","Weight",new_weight);
OGSNTweakItem("spraypaint.ChalkOrange","Weight",new_weight);
OGSNTweakItem("spraypaint.ChalkYellow","Weight",new_weight);
OGSNTweakItem("spraypaint.ChalkViolet","Weight",new_weight);
OGSNTweakItem("spraypaint.ChalkCyan","Weight",new_weight);
