require("ItemTweaker_Copy_ogsn");
local new_weight = "0.1"
TweakItem("spraypaint.SpraycanWhite","Weight",new_weight);
TweakItem("spraypaint.SpraycanRed","Weight",new_weight);
TweakItem("spraypaint.SpraycanBlue","Weight",new_weight);
TweakItem("spraypaint.SpraycanGreen","Weight",new_weight);
TweakItem("spraypaint.SpraycanOrange","Weight",new_weight);
TweakItem("spraypaint.SpraycanYellow","Weight",new_weight);
TweakItem("spraypaint.SpraycanViolet","Weight",new_weight);
TweakItem("spraypaint.SpraycanBlack","Weight",new_weight);
TweakItem("spraypaint.SpraycanCyan","Weight",new_weight);
TweakItem("spraypaint.ChalkWhite","Weight",new_weight);
TweakItem("spraypaint.ChalkRed","Weight",new_weight);
TweakItem("spraypaint.ChalkBlue","Weight",new_weight);
TweakItem("spraypaint.ChalkGreen","Weight",new_weight);
TweakItem("spraypaint.ChalkOrange","Weight",new_weight);
TweakItem("spraypaint.ChalkYellow","Weight",new_weight);
TweakItem("spraypaint.ChalkViolet","Weight",new_weight);
TweakItem("spraypaint.ChalkCyan","Weight",new_weight);
