require "Traps/TrapDefinition"

local pheasant = {};
pheasant.type = "pheasant";
pheasant.strength = 30;
pheasant.item = "FMJ.DeadPheasant";
pheasant.minHour = 0;
pheasant.maxHour = 0;
pheasant.minSize = 25;
pheasant.maxSize = 60;
pheasant.zone = {};
pheasant.zone["TownZone"] = 2;
pheasant.zone["TrailerPark"] = 2;
pheasant.zone["Vegitation"] = 10;
pheasant.zone["Forest"] = 12;
pheasant.zone["DeepForest"] = 15;
pheasant.traps = {};
pheasant.traps["Base.TrapCage"] = 20;
pheasant.traps["Base.TrapSnare"] = 10;
pheasant.traps["Base.TrapBox"] = 10;
pheasant.traps["Base.TrapCrate"] = 10;
pheasant.baits = {};
pheasant.baits["Base.Popcorn"] = 25;
pheasant.baits["Base.Bread"] = 15;
pheasant.baits["Base.Breadslices"] = 15;
pheasant.baits["Base.Worm"] = 30;
pheasant.baits["Base.Corn"] = 15;
pheasant.baits["Base.Cereal"] = 20;
pheasant.baits["Base.Cricket"] = 25;
pheasant.baits["Base.Cockroach"] = 25;
pheasant.baits["Base.Grasshopper"] = 25;
pheasant.baits["Base.SunflowerSeeds"] = 20;
pheasant.baits["FMJ.WheatGrains"] = 20;

local lizard = {};
lizard.type = "lizard";
lizard.item = "FMJ.DeadLizard";
lizard.minHour = 0;
lizard.maxHour = 0;
lizard.minSize = 10;
lizard.maxSize = 20;
lizard.zone = {};
lizard.zone["FarmLand"] = 5;
lizard.zone["TownZone"] = 2;
lizard.zone["TrailerPark"] = 5;
lizard.zone["Vegitation"] = 15;
lizard.zone["Forest"] = 20;
lizard.zone["DeepForest"] = 25;
lizard.traps = {};
lizard.traps["Base.TrapMouse"] = 20;
lizard.baits = {};
lizard.baits["Worm"] = 10;
lizard.baits["Base.Cricket"] = 10;
lizard.baits["Base.Cockroach"] = 10;
lizard.baits["Base.Grasshopper"] = 10;

local snake = {};
snake.type = "snake";
snake.item = "FMJ.DeadSnake";
snake.minHour = 0;
snake.maxHour = 0;
snake.minSize = 12;
snake.maxSize = 45;
snake.zone = {};
snake.zone["FarmLand"] = 10;
snake.zone["TownZone"] = 2;
snake.zone["TrailerPark"] = 2;
snake.zone["Vegitation"] = 15;
snake.zone["Forest"] = 15;
snake.zone["DeepForest"] = 20;
snake.traps = {};
snake.traps["Base.TrapCrate"] = 15;
snake.traps["Base.TrapBox"] = 15;
snake.baits = {};
snake.baits["Base.WildEggs"] = 10;
snake.baits["Base.Egg"] = 10;
snake.baits["FMJ.DeadLizard"] = 15;
snake.baits["Base.DeadRat"] = 20;
snake.baits["Base.DeadMouse"] = 20;

table.insert(Animals, pheasant);
table.insert(Animals, lizard);
table.insert(Animals, snake);
