require 'Items/Distributions'
require 'Items/ProceduralDistributions'

table.insert(Distributions["burgerkitchen"]["fridge"].items, "FMJ.PotatoPancakes");
table.insert(Distributions["burgerkitchen"]["fridge"].items, 4);
table.insert(Distributions["burgerkitchen"]["counter"].items, "FMJ.PotatoPancakes");
table.insert(Distributions["burgerkitchen"]["counter"].items, 4);

table.insert(Distributions["zippeestore"]["counter"].items, "FMJ.Herbs");
table.insert(Distributions["zippeestore"]["counter"].items, 2);
table.insert(ProceduralDistributions["list"]["KitchenDryFood"].items, "FMJ.Herbs");
table.insert(ProceduralDistributions["list"]["KitchenDryFood"].items, 3);
table.insert(Distributions["all"]["dishescabinet"].items, "FMJ.Herbs");
table.insert(Distributions["all"]["dishescabinet"].items, 5);
table.insert(Distributions["spiffoskitchen"]["counter"].items, "FMJ.Herbs");
table.insert(Distributions["spiffoskitchen"]["counter"].items, 5);
table.insert(Distributions["restaurantkitchen"]["counter"].items, "FMJ.Herbs");
table.insert(Distributions["restaurantkitchen"]["counter"].items, 5);
table.insert(Distributions["generalstore"]["other"].items, "FMJ.Herbs");
table.insert(Distributions["generalstore"]["other"].items, 5);
table.insert(Distributions["generalstorestorage"]["other"].items, "FMJ.Herbs");
table.insert(Distributions["generalstorestorage"]["other"].items, 5);
table.insert(ProceduralDistributions["list"]["GigamartDryGoods"].junk, "FMJ.Herbs");
table.insert(ProceduralDistributions["list"]["GigamartDryGoods"].junk, 3);
table.insert(Distributions["storageunit"]["all"].items, "FMJ.Herbs");
table.insert(Distributions["storageunit"]["all"].items, 1);

table.insert(Distributions["kitchen_crepe"]["fridge"].items, "FMJ.PotatoPancakes");
table.insert(Distributions["kitchen_crepe"]["fridge"].items, 3);
table.insert(Distributions["all"]["fridge"].items, "FMJ.PotatoPancakes");
table.insert(Distributions["all"]["fridge"].items, 4);
table.insert(Distributions["spiffosstorage"]["all"].items, "FMJ.PotatoPancakes");
table.insert(Distributions["spiffosstorage"]["all"].items, 5);
table.insert(Distributions["spiffoskitchen"]["fridge"].items, "FMJ.PotatoPancakes");
table.insert(Distributions["spiffoskitchen"]["fridge"].items, 5);
table.insert(Distributions["bakery"]["counter"].items, "FMJ.PotatoPancakes");
table.insert(Distributions["bakery"]["counter"].items, 5);
table.insert(Distributions["bakery"]["grocerstand"].items, "FMJ.PotatoPancakes");
table.insert(Distributions["bakery"]["grocerstand"].items, 5);
table.insert(ProceduralDistributions["list"]["Bakery"].items, "FMJ.PotatoPancakes");
table.insert(ProceduralDistributions["list"]["Bakery"].items, 5);
table.insert(ProceduralDistributions["list"]["Bakery"].items, "FMJ.PotatoPancakes");
table.insert(ProceduralDistributions["list"]["Bakery"].items, 5);
table.insert(Distributions["cafe"]["counter"].items, "FMJ.PotatoPancakes");
table.insert(Distributions["cafe"]["counter"].items, 5);
table.insert(Distributions["cafe"]["displaycase"].items, "FMJ.PotatoPancakes");
table.insert(Distributions["cafe"]["displaycase"].items, 5);
table.insert(Distributions["cafekitchen"]["all"].items, "FMJ.PotatoPancakes");
table.insert(Distributions["cafekitchen"]["all"].items, 5);
table.insert(Distributions["pizzakitchen"]["fridge"].items, "FMJ.PotatoPancakes");
table.insert(Distributions["pizzakitchen"]["fridge"].items, 5);
table.insert(Distributions["camping"]["fridge"].items, "FMJ.PotatoPancakes");
table.insert(Distributions["camping"]["fridge"].items, 2);

table.insert(Distributions["kitchen_crepe"]["fridge"].items, "FMJ.Omelettes");
table.insert(Distributions["kitchen_crepe"]["fridge"].items, 3);
table.insert(Distributions["all"]["fridge"].items, "FMJ.Omelettes");
table.insert(Distributions["all"]["fridge"].items, 4);
table.insert(Distributions["spiffosstorage"]["all"].items, "FMJ.Omelettes");
table.insert(Distributions["spiffosstorage"]["all"].items, 5);
table.insert(Distributions["spiffoskitchen"]["fridge"].items, "FMJ.Omelettes");
table.insert(Distributions["spiffoskitchen"]["fridge"].items, 5);
table.insert(Distributions["cafekitchen"]["all"].items, "FMJ.Omelettes");
table.insert(Distributions["cafekitchen"]["all"].items, 5);
table.insert(Distributions["pizzakitchen"]["fridge"].items, "FMJ.Omelettes");
table.insert(Distributions["pizzakitchen"]["fridge"].items, 5);
table.insert(Distributions["camping"]["fridge"].items, "FMJ.Omelettes");
table.insert(Distributions["camping"]["fridge"].items, 2);
