require "Farming/ScavengeDefinition";

local Nettle = {};
Nettle.type = "FMJ.Nettle";
Nettle.minCount = 1;
Nettle.maxCount = 3;
Nettle.skill = 3;
local WildPotatoes = {};
WildPotatoes.type = "FMJ.WildPotatoes";
WildPotatoes.minCount = 1;
WildPotatoes.maxCount = 2;
WildPotatoes.skill = 5;
local WildCarrots = {};
WildCarrots.type = "FMJ.WildCarrots";
WildCarrots.minCount = 1;
WildCarrots.maxCount = 2;
WildCarrots.skill = 5;
local Herbs = {};
Herbs.type = "FMJ.Herbs";
Herbs.minCount = 1;
Herbs.maxCount = 2;
Herbs.skill = 3;
local Tobacco = {};
Tobacco.type = "FMJ.Tobacco";
Tobacco.minCount = 1;
Tobacco.maxCount = 3;
Tobacco.skill = 2;
local BirchBark = {};
BirchBark.type = "FMJ.BirchBark";
BirchBark.minCount = 1;
BirchBark.maxCount = 3;
BirchBark.skill = 1;
local WildWheat = {};
WildWheat.type = "FMJ.WildWheat";
WildWheat.minCount = 1;
WildWheat.maxCount = 1;
WildWheat.skill = 5;
local Dandelions = {};
Dandelions.type = "FMJ.Dandelions";
Dandelions.minCount = 1;
Dandelions.maxCount = 2;
Dandelions.skill = 1;
local WildCorn = {};
WildCorn.type = "FMJ.WildCorn";
WildCorn.minCount = 1;
WildCorn.maxCount = 2;
WildCorn.skill = 4;


table.insert(scavenges.medicinalPlants, Nettle);
table.insert(scavenges.medicinalPlants, Herbs);
table.insert(scavenges.mushrooms, WildPotatoes);
table.insert(scavenges.mushrooms, WildCarrots);
table.insert(scavenges.medicinalPlants, Tobacco);
table.insert(scavenges.forestGoods, BirchBark);
table.insert(scavenges.forestGoods, WildWheat);
table.insert(scavenges.mushrooms, WildWheat);
table.insert(scavenges.mushrooms, Dandelions);
table.insert(scavenges.berries, Dandelions);
table.insert(scavenges.berries, WildCorn);