require 'Items/Distributions'
require 'Items/ProceduralDistributions'

ProceduralDistributions = ProceduralDistributions or {}
SuburbsDistributions = SuburbsDistributions or {}

local function stockIWBUMS()
  -- not necessary, vanilla distro is pretty good
  -- let me know in the comments if you disagree
end

local function stockClassic()
  -- Police station
  table.insert(SuburbsDistributions["policestorage"]["locker"].items, "9mmClip");
  table.insert(SuburbsDistributions["policestorage"]["locker"].items, 1.5);
  table.insert(SuburbsDistributions["policestorage"]["locker"].items, "44Clip");
  table.insert(SuburbsDistributions["policestorage"]["locker"].items, 1.5);
  table.insert(SuburbsDistributions["policestorage"]["locker"].items, "45Clip");
  table.insert(SuburbsDistributions["policestorage"]["locker"].items, 1.5);
  table.insert(SuburbsDistributions["policestorage"]["locker"].items, "223Clip");
  table.insert(SuburbsDistributions["policestorage"]["locker"].items, 1.5);
  table.insert(SuburbsDistributions["policestorage"]["locker"].items, "308Clip");
  table.insert(SuburbsDistributions["policestorage"]["locker"].items, 1.5);
  table.insert(SuburbsDistributions["policestorage"]["metal_shelves"].items, "9mmClip");
  table.insert(SuburbsDistributions["policestorage"]["metal_shelves"].items, 1.5);
  table.insert(SuburbsDistributions["policestorage"]["metal_shelves"].items, "44Clip");
  table.insert(SuburbsDistributions["policestorage"]["metal_shelves"].items, 1.5);
  table.insert(SuburbsDistributions["policestorage"]["metal_shelves"].items, "45Clip");
  table.insert(SuburbsDistributions["policestorage"]["metal_shelves"].items, 1.5);
  table.insert(SuburbsDistributions["policestorage"]["metal_shelves"].items, "223Clip");
  table.insert(SuburbsDistributions["policestorage"]["metal_shelves"].items, 1.5);
  table.insert(SuburbsDistributions["policestorage"]["metal_shelves"].items, "308Clip");
  table.insert(SuburbsDistributions["policestorage"]["metal_shelves"].items, 1.5);
  -- Army base
  table.insert(SuburbsDistributions["armystorage"]["locker"].items, "9mmClip");
  table.insert(SuburbsDistributions["armystorage"]["locker"].items, 1.5);
  table.insert(SuburbsDistributions["armystorage"]["locker"].items, "44Clip");
  table.insert(SuburbsDistributions["armystorage"]["locker"].items, 1.5);
  table.insert(SuburbsDistributions["armystorage"]["locker"].items, "45Clip");
  table.insert(SuburbsDistributions["armystorage"]["locker"].items, 1.5);
  table.insert(SuburbsDistributions["armystorage"]["locker"].items, "223Clip");
  table.insert(SuburbsDistributions["armystorage"]["locker"].items, 1.5);
  table.insert(SuburbsDistributions["armystorage"]["locker"].items, "308Clip");
  table.insert(SuburbsDistributions["armystorage"]["locker"].items, 1.5);
  table.insert(SuburbsDistributions["armystorage"]["metal_shelves"].items, "9mmClip");
  table.insert(SuburbsDistributions["armystorage"]["metal_shelves"].items, 1.5);
  table.insert(SuburbsDistributions["armystorage"]["metal_shelves"].items, "44Clip");
  table.insert(SuburbsDistributions["armystorage"]["metal_shelves"].items, 1.5);
  table.insert(SuburbsDistributions["armystorage"]["metal_shelves"].items, "45Clip");
  table.insert(SuburbsDistributions["armystorage"]["metal_shelves"].items, 1.5);
  table.insert(SuburbsDistributions["armystorage"]["metal_shelves"].items, "223Clip");
  table.insert(SuburbsDistributions["armystorage"]["metal_shelves"].items, 1.5);
  table.insert(SuburbsDistributions["armystorage"]["metal_shelves"].items, "308Clip");
  table.insert(SuburbsDistributions["armystorage"]["metal_shelves"].items, 1.5);
  -- Gunstore
  table.insert(SuburbsDistributions["gunstore"]["counter"].items, "9mmClip");
  table.insert(SuburbsDistributions["gunstore"]["counter"].items, 4);
  table.insert(SuburbsDistributions["gunstore"]["counter"].items, "44Clip");
  table.insert(SuburbsDistributions["gunstore"]["counter"].items, 4);
  table.insert(SuburbsDistributions["gunstore"]["counter"].items, "45Clip");
  table.insert(SuburbsDistributions["gunstore"]["counter"].items, 4);
  table.insert(SuburbsDistributions["gunstore"]["counter"].items, "223Clip");
  table.insert(SuburbsDistributions["gunstore"]["counter"].items, 4);
  table.insert(SuburbsDistributions["gunstore"]["counter"].items, "308Clip");
  table.insert(SuburbsDistributions["gunstore"]["counter"].items, 4);
  table.insert(SuburbsDistributions["gunstore"]["displaycase"].items, "9mmClip");
  table.insert(SuburbsDistributions["gunstore"]["displaycase"].items, 4);
  table.insert(SuburbsDistributions["gunstore"]["displaycase"].items, "44Clip");
  table.insert(SuburbsDistributions["gunstore"]["displaycase"].items, 4);
  table.insert(SuburbsDistributions["gunstore"]["displaycase"].items, "45Clip");
  table.insert(SuburbsDistributions["gunstore"]["displaycase"].items, 4);
  table.insert(SuburbsDistributions["gunstore"]["displaycase"].items, "223Clip");
  table.insert(SuburbsDistributions["gunstore"]["displaycase"].items, 4);
  table.insert(SuburbsDistributions["gunstore"]["displaycase"].items, "308Clip");
  table.insert(SuburbsDistributions["gunstore"]["displaycase"].items, 4);
  table.insert(SuburbsDistributions["gunstore"]["locker"].items, "9mmClip");
  table.insert(SuburbsDistributions["gunstore"]["locker"].items, 4);
  table.insert(SuburbsDistributions["gunstore"]["locker"].items, "44Clip");
  table.insert(SuburbsDistributions["gunstore"]["locker"].items, 4);
  table.insert(SuburbsDistributions["gunstore"]["locker"].items, "45Clip");
  table.insert(SuburbsDistributions["gunstore"]["locker"].items, 4);
  table.insert(SuburbsDistributions["gunstore"]["locker"].items, "223Clip");
  table.insert(SuburbsDistributions["gunstore"]["locker"].items, 4);
  table.insert(SuburbsDistributions["gunstore"]["locker"].items, "308Clip");
  table.insert(SuburbsDistributions["gunstore"]["locker"].items, 4);
  table.insert(SuburbsDistributions["gunstore"]["metal_shelves"].items, "9mmClip");
  table.insert(SuburbsDistributions["gunstore"]["metal_shelves"].items, 4);
  table.insert(SuburbsDistributions["gunstore"]["metal_shelves"].items, "44Clip");
  table.insert(SuburbsDistributions["gunstore"]["metal_shelves"].items, 4);
  table.insert(SuburbsDistributions["gunstore"]["metal_shelves"].items, "45Clip");
  table.insert(SuburbsDistributions["gunstore"]["metal_shelves"].items, 4);
  table.insert(SuburbsDistributions["gunstore"]["metal_shelves"].items, "223Clip");
  table.insert(SuburbsDistributions["gunstore"]["metal_shelves"].items, 4);
  table.insert(SuburbsDistributions["gunstore"]["metal_shelves"].items, "308Clip");
  table.insert(SuburbsDistributions["gunstore"]["metal_shelves"].items, 4);
  table.insert(SuburbsDistributions["gunstorestorage"]["all"].items, "9mmClip");
  table.insert(SuburbsDistributions["gunstorestorage"]["all"].items, 4);
  table.insert(SuburbsDistributions["gunstorestorage"]["all"].items, "44Clip");
  table.insert(SuburbsDistributions["gunstorestorage"]["all"].items, 4);
  table.insert(SuburbsDistributions["gunstorestorage"]["all"].items, "45Clip");
  table.insert(SuburbsDistributions["gunstorestorage"]["all"].items, 4);
  table.insert(SuburbsDistributions["gunstorestorage"]["all"].items, "223Clip");
  table.insert(SuburbsDistributions["gunstorestorage"]["all"].items, 4);
  table.insert(SuburbsDistributions["gunstorestorage"]["all"].items, "308Clip");
  table.insert(SuburbsDistributions["gunstorestorage"]["all"].items, 4);
  -- Weaponbag
  table.insert(SuburbsDistributions["Bag_WeaponBag"].items, "9mmClip");
  table.insert(SuburbsDistributions["Bag_WeaponBag"].items, 10);
  table.insert(SuburbsDistributions["Bag_WeaponBag"].items, "44Clip");
  table.insert(SuburbsDistributions["Bag_WeaponBag"].items, 10);
  table.insert(SuburbsDistributions["Bag_WeaponBag"].items, "45Clip");
  table.insert(SuburbsDistributions["Bag_WeaponBag"].items, 10);
  table.insert(SuburbsDistributions["Bag_WeaponBag"].items, "223Clip");
  table.insert(SuburbsDistributions["Bag_WeaponBag"].items, 10);
  table.insert(SuburbsDistributions["Bag_WeaponBag"].items, "308Clip");
  table.insert(SuburbsDistributions["Bag_WeaponBag"].items, 10);
  -- GunCache1
  table.insert(SuburbsDistributions["GunCache1"]["GunBox"].items, "9mmClip");
  table.insert(SuburbsDistributions["GunCache1"]["GunBox"].items, 10);
  table.insert(SuburbsDistributions["GunCache1"]["GunBox"].items, "44Clip");
  table.insert(SuburbsDistributions["GunCache1"]["GunBox"].items, 10);
  table.insert(SuburbsDistributions["GunCache1"]["GunBox"].items, "45Clip");
  table.insert(SuburbsDistributions["GunCache1"]["GunBox"].items, 10);
  table.insert(SuburbsDistributions["GunCache1"]["GunBox"].items, "223Clip");
  table.insert(SuburbsDistributions["GunCache1"]["GunBox"].items, 10);
  table.insert(SuburbsDistributions["GunCache1"]["GunBox"].items, "308Clip");
  table.insert(SuburbsDistributions["GunCache1"]["GunBox"].items, 10);
  table.insert(SuburbsDistributions["GunCache1"]["Bag_DuffelBagTINT"].items, "9mmClip");
  table.insert(SuburbsDistributions["GunCache1"]["Bag_DuffelBagTINT"].items, 10);
  table.insert(SuburbsDistributions["GunCache1"]["Bag_DuffelBagTINT"].items, "44Clip");
  table.insert(SuburbsDistributions["GunCache1"]["Bag_DuffelBagTINT"].items, 10);
  table.insert(SuburbsDistributions["GunCache1"]["Bag_DuffelBagTINT"].items, "45Clip");
  table.insert(SuburbsDistributions["GunCache1"]["Bag_DuffelBagTINT"].items, 10);
  table.insert(SuburbsDistributions["GunCache1"]["Bag_DuffelBagTINT"].items, "223Clip");
  table.insert(SuburbsDistributions["GunCache1"]["Bag_DuffelBagTINT"].items, 10);
  table.insert(SuburbsDistributions["GunCache1"]["Bag_DuffelBagTINT"].items, "308Clip");
  table.insert(SuburbsDistributions["GunCache1"]["Bag_DuffelBagTINT"].items, 10);
  table.insert(SuburbsDistributions["GunCache1"]["Bag_DuffelBagTINT"].items, "9mmClip");
  table.insert(SuburbsDistributions["GunCache1"]["Bag_DuffelBagTINT"].items, 10);
  table.insert(SuburbsDistributions["GunCache1"]["Bag_DuffelBagTINT"].items, "44Clip");
  table.insert(SuburbsDistributions["GunCache1"]["Bag_DuffelBagTINT"].items, 10);
  table.insert(SuburbsDistributions["GunCache1"]["Bag_DuffelBagTINT"].items, "45Clip");
  table.insert(SuburbsDistributions["GunCache1"]["Bag_DuffelBagTINT"].items, 10);
  table.insert(SuburbsDistributions["GunCache1"]["Bag_DuffelBagTINT"].items, "223Clip");
  table.insert(SuburbsDistributions["GunCache1"]["Bag_DuffelBagTINT"].items, 10);
  table.insert(SuburbsDistributions["GunCache1"]["Bag_DuffelBagTINT"].items, "308Clip");
  table.insert(SuburbsDistributions["GunCache1"]["Bag_DuffelBagTINT"].items, 10);
  -- GunCache2
  table.insert(SuburbsDistributions["GunCache2"]["GunBox"].items, "9mmClip");
  table.insert(SuburbsDistributions["GunCache2"]["GunBox"].items, 10);
  table.insert(SuburbsDistributions["GunCache2"]["GunBox"].items, "44Clip");
  table.insert(SuburbsDistributions["GunCache2"]["GunBox"].items, 10);
  table.insert(SuburbsDistributions["GunCache2"]["GunBox"].items, "45Clip");
  table.insert(SuburbsDistributions["GunCache2"]["GunBox"].items, 10);
  table.insert(SuburbsDistributions["GunCache2"]["GunBox"].items, "223Clip");
  table.insert(SuburbsDistributions["GunCache2"]["GunBox"].items, 10);
  table.insert(SuburbsDistributions["GunCache2"]["GunBox"].items, "308Clip");
  table.insert(SuburbsDistributions["GunCache2"]["GunBox"].items, 10);
  table.insert(SuburbsDistributions["GunCache2"]["Bag_DuffelBagTINT"].items, "9mmClip");
  table.insert(SuburbsDistributions["GunCache2"]["Bag_DuffelBagTINT"].items, 10);
  table.insert(SuburbsDistributions["GunCache2"]["Bag_DuffelBagTINT"].items, "44Clip");
  table.insert(SuburbsDistributions["GunCache2"]["Bag_DuffelBagTINT"].items, 10);
  table.insert(SuburbsDistributions["GunCache2"]["Bag_DuffelBagTINT"].items, "45Clip");
  table.insert(SuburbsDistributions["GunCache2"]["Bag_DuffelBagTINT"].items, 10);
  table.insert(SuburbsDistributions["GunCache2"]["Bag_DuffelBagTINT"].items, "223Clip");
  table.insert(SuburbsDistributions["GunCache2"]["Bag_DuffelBagTINT"].items, 10);
  table.insert(SuburbsDistributions["GunCache2"]["Bag_DuffelBagTINT"].items, "308Clip");
  table.insert(SuburbsDistributions["GunCache2"]["Bag_DuffelBagTINT"].items, 10);
  table.insert(SuburbsDistributions["GunCache2"]["Bag_DuffelBagTINT"].items, "9mmClip");
  table.insert(SuburbsDistributions["GunCache2"]["Bag_DuffelBagTINT"].items, 10);
  table.insert(SuburbsDistributions["GunCache2"]["Bag_DuffelBagTINT"].items, "44Clip");
  table.insert(SuburbsDistributions["GunCache2"]["Bag_DuffelBagTINT"].items, 10);
  table.insert(SuburbsDistributions["GunCache2"]["Bag_DuffelBagTINT"].items, "45Clip");
  table.insert(SuburbsDistributions["GunCache2"]["Bag_DuffelBagTINT"].items, 10);
  table.insert(SuburbsDistributions["GunCache2"]["Bag_DuffelBagTINT"].items, "223Clip");
  table.insert(SuburbsDistributions["GunCache2"]["Bag_DuffelBagTINT"].items, 10);
  table.insert(SuburbsDistributions["GunCache2"]["Bag_DuffelBagTINT"].items, "308Clip");
  table.insert(SuburbsDistributions["GunCache2"]["Bag_DuffelBagTINT"].items, 10);
  -- security
  table.insert(SuburbsDistributions["security"]["locker"].items, "9mmClip");
  table.insert(SuburbsDistributions["security"]["locker"].items, 5);
  table.insert(SuburbsDistributions["security"]["locker"].items, "44Clip");
  table.insert(SuburbsDistributions["security"]["locker"].items, 5);
  table.insert(SuburbsDistributions["security"]["locker"].items, "45Clip");
  table.insert(SuburbsDistributions["security"]["locker"].items, 5);
  table.insert(SuburbsDistributions["security"]["locker"].items, "223Clip");
  table.insert(SuburbsDistributions["security"]["locker"].items, 5);
  table.insert(SuburbsDistributions["security"]["locker"].items, "308Clip");
  table.insert(SuburbsDistributions["security"]["locker"].items, 5);
end

if string.match(getCore():getVersionNumber(), "41")
  then stockIWBUMS();
  else stockClassic();
end;
