require("ItemTweaker_Copy_ogsn");
-- Some of these aren't necessary but I will do them all anyway
OGSNTweakItem("Base.Hat_Bandana","DisplayName","Bandana");
OGSNTweakItem("Base.Hat_BandanaTied","DisplayName","Bandana (Rambo)");
OGSNTweakItem("Base.Hat_BandanaTINT","DisplayName","Bandana - Plain");
OGSNTweakItem("Base.Hat_BandanaTiedTINT","DisplayName","Bandana - Plain (Rambo)");
OGSNTweakItem("Base.Hat_BaseballCap","DisplayName","Baseball Cap");
OGSNTweakItem("Base.Hat_BaseballCap_Reverse","DisplayName","Baseball Cap");
OGSNTweakItem("Base.Hat_BaseballCapBlue","DisplayName","Baseball Cap");
OGSNTweakItem("Base.Hat_BaseballCapBlue_Reverse","DisplayName","Baseball Cap");
OGSNTweakItem("Base.Hat_BaseballCapRed","DisplayName","Baseball Cap");
OGSNTweakItem("Base.Hat_BaseballCapRed_Reverse","DisplayName","Baseball Cap");
OGSNTweakItem("Base.Hat_BaseballCapGreen","DisplayName","Baseball Cap");
OGSNTweakItem("Base.Hat_BaseballCapGreen_Reverse","DisplayName","Baseball Cap");
OGSNTweakItem("Base.Hat_BaseballCapArmy,","DisplayName","Baseball Cap Army");
OGSNTweakItem("Base.Hat_BaseballCapArmy_Reverse,","DisplayName","Baseball Cap Army");
OGSNTweakItem("Base.Hat_BaseballCapKY","DisplayName","Baseball Cap KY");
OGSNTweakItem("Base.Hat_BaseballCapKY_Reverse","DisplayName","Baseball Cap KY");
OGSNTweakItem("Base.Hat_BaseballCapKY_Red","DisplayName","Baseball Cap KY");
OGSNTweakItem("Base.Hat_Beany","DisplayName","Beanie");
OGSNTweakItem("Base.Hat_Beret","DisplayName","Beret");
OGSNTweakItem("Base.Hat_BeretArmy","DisplayName","Beret - Army");
OGSNTweakItem("Base.Hat_BonnieHat_CamoGreen","DisplayName","Bonnie Hat Camo");
OGSNTweakItem("Base.Hat_BonnieHat","DisplayName","Bonnie Hat Green");
OGSNTweakItem("Base.Hat_ChefHat","DisplayName","Chef Hat");
OGSNTweakItem("Base.Hat_Cowboy","DisplayName","Cowboy Hat");
OGSNTweakItem("Base.Hat_EarMuffs","DisplayName","Ear Muffs");
OGSNTweakItem("Base.Hat_EarMuff_Protectors","DisplayName","Ear Protectors");
OGSNTweakItem("Base.Hat_Fedora","DisplayName","Fedora");
OGSNTweakItem("Base.Hat_Fedora_Delmonte","DisplayName","Fedora - Black Band");
OGSNTweakItem("Base.Hat_Ranger","DisplayName","Flat Hat - Park Ranger");
OGSNTweakItem("Base.Hat_Police_Grey","DisplayName","Flat Hat - Police Deputy");
OGSNTweakItem("Base.Hat_Police","DisplayName","Flat Hat - Police Trooper");
OGSNTweakItem("Base.Hat_GolfHatTINT","DisplayName","Golf Cap");
OGSNTweakItem("Base.Hat_GolfHat","DisplayName","Golf Cap - Tartan");
OGSNTweakItem("Base.Hat_HardHat","DisplayName","Hard Hat");
OGSNTweakItem("Base.Hat_HardHat_Miner","DisplayName","Hard Hat - Mining");
OGSNTweakItem("Base.Hat_Army","DisplayName","Helmet - Army");
OGSNTweakItem("Base.Hat_BaseballHelmet_KY","DisplayName","Helmet - Baseball Kentucky");
OGSNTweakItem("Base.Hat_BaseballHelmet_Rangers","DisplayName","Helmet - Baseball Riverside Rangers");
OGSNTweakItem("Base.Hat_BaseballHelmet_Z","DisplayName","Helmet - Baseball Z Hurricanes");
OGSNTweakItem("Base.Hat_BicycleHelmet","DisplayName","Helmet - Bicycle");
OGSNTweakItem("Base.Hat_CrashHelmet","DisplayName","Helmet - Crash");
OGSNTweakItem("Base.Hat_CrashHelmet_Police","DisplayName","Helmet - Crash Police");
OGSNTweakItem("Base.Hat_CrashHelmet_Stars","DisplayName","Helmet - Crash USA");
OGSNTweakItem("Base.Hat_Fireman","DisplayName","Helmet - Firefighter");
OGSNTweakItem("Base.Hat_HockeyHelmet","DisplayName","Helmet - Hockey");
OGSNTweakItem("Base.Hat_JockeyHelmet01","DisplayName","Helmet - Jockey #1");
OGSNTweakItem("Base.Hat_JockeyHelmet02","DisplayName","Helmet - Jockey #2");
OGSNTweakItem("Base.Hat_JockeyHelmet03","DisplayName","Helmet - Jockey #3");
OGSNTweakItem("Base.Hat_JockeyHelmet04","DisplayName","Helmet - Jockey #4");
OGSNTweakItem("Base.Hat_JockeyHelmet05","DisplayName","Helmet - Jockey #5");
OGSNTweakItem("Base.Hat_JockeyHelmet06","DisplayName","Helmet - Jockey #6");
OGSNTweakItem("Base.Hat_RidingHelmet","DisplayName","Helmet - Riding");
OGSNTweakItem("Base.Hat_PartyHat_TINT","DisplayName","Party Hat");
OGSNTweakItem("Base.Hat_PeakedCapArmy","DisplayName","Peaked Cap - Army");
OGSNTweakItem("Base.Hat_Raccoon","DisplayName","Raccoon Skin Hat");
OGSNTweakItem("Base.Hat_FastFood","DisplayName","Server Hat - Fast Food");
OGSNTweakItem("Base.Hat_FastFood_IceCream","DisplayName","Server Hat - Ice Cream");
OGSNTweakItem("Base.Hat_FastFood_Spiffo","DisplayName","Server Hat - Spiffo's");
OGSNTweakItem("Base.Hat_SantaHat","DisplayName","Santa Hat - Red");
OGSNTweakItem("Base.Hat_SantaHatGreen","DisplayName","Santa Hat - Green");
OGSNTweakItem("Base.Hat_ShowerCap","DisplayName","Shower Cap");
OGSNTweakItem("Base.Hat_SummerHat","DisplayName","Summer Hat");
OGSNTweakItem("Base.Hat_SurgicalCap_Blue","DisplayName","Surgical Cap - Blue");
OGSNTweakItem("Base.Hat_SurgicalCap_Green","DisplayName","Surgical Cap - Green");
OGSNTweakItem("Base.Hat_Sweatband","DisplayName","Sweatband");
OGSNTweakItem("Base.Hat_WeddingVeil","DisplayName","Wedding Veil");
OGSNTweakItem("Base.Hat_WinterHat","DisplayName","Winter Hat");
OGSNTweakItem("Base.Hat_WoolyHat","DisplayName","Woolly Hat");
OGSNTweakItem("Base.Hat_Visor_WhiteTINT","DisplayName","Visor");
OGSNTweakItem("Base.Hat_VisorBlack","DisplayName","Visor - Black");
OGSNTweakItem("Base.Hat_VisorRed","DisplayName","Visor - Red");
