require("ItemTweaker_Copy_ogsn");
-- TweakItem("Module.ItemName","AttributeName","New Attribute Value");

-- Some of these aren't necessary but I will do them all anyway
TweakItem("Base.Tshirt_DefaultTEXTURE","DisplayName","Plain");
TweakItem("Base.Tshirt_DefaultTEXTURE_TINT","DisplayName","Plain");
TweakItem("Base.Tshirt_WhiteTINT","DisplayName","Plain");
TweakItem("Base.Tshirt_WhiteLongSleeve","DisplayName","Plain Long Sleeve");
TweakItem("Base.Tshirt_WhiteLongSleeveTINT","DisplayName","Plain Long Sleeve");
TweakItem("Base.Tshirt_PoloStripedTINT","DisplayName","Striped");
TweakItem("Base.Tshirt_PoloTINT","DisplayName","Polo");
TweakItem("Base.Tshirt_DefaultDECAL","DisplayName","Random Decal");
TweakItem("Base.Tshirt_DefaultDECAL_TINT","DisplayName","Random Decal");
TweakItem("Base.Tshirt_SportDECAL","DisplayName","Random Decal - Sport");
TweakItem("Base.Tshirt_Rock","DisplayName","Rock");
TweakItem("Base.Tshirt_Sport","DisplayName","Sport");
TweakItem("Base.Tshirt_ArmyGreen","DisplayName","Army");
TweakItem("Base.Tshirt_CamoDesert","DisplayName","Army Camo Desert");
TweakItem("Base.Tshirt_CamoGreen","DisplayName","Army Camo Forest");
TweakItem("Base.Tshirt_CamoUrban","DisplayName","Army Camo Urban");
TweakItem("Base.Tshirt_Fossoil","DisplayName","Fossoil");
TweakItem("Base.Tshirt_Gas2Go","DisplayName","Gas2Go");
TweakItem("Base.Tshirt_McCoys","DisplayName","McCoys");
TweakItem("Base.Tshirt_PileOCrepe","DisplayName","PileOCrepe");
TweakItem("Base.Tshirt_PizzaWhirled","DisplayName","Pizza Whirled");
TweakItem("Base.Tshirt_BusinessSpiffo","DisplayName","Spiffo Business");
TweakItem("Base.Tshirt_SpiffoDECAL","DisplayName","Spiffo Decal");
TweakItem("Base.Tshirt_ThunderGas","DisplayName","ThunderGas");
TweakItem("Base.Tshirt_ValleyStation","DisplayName","Valley Station");
TweakItem("Base.Tshirt_IndieStoneDECAL","DisplayName","The Indie Stone");
TweakItem("Base.Tshirt_Profession_FiremanBlue","DisplayName","Fireman - Blue");
TweakItem("Base.Tshirt_Profession_FiremanRed02","DisplayName","Fireman - Dark Red");
TweakItem("Base.Tshirt_Profession_FiremanRed","DisplayName","Fireman - Light Red");
TweakItem("Base.Tshirt_Profession_FiremanWhite","DisplayName","Fireman - White");
TweakItem("Base.Tshirt_Scrubs","DisplayName","Medical");
TweakItem("Base.Tshirt_Ranger","DisplayName","Park Ranger");
TweakItem("Base.Tshirt_Profession_RangerBrown","DisplayName","Park Ranger - Brown");
TweakItem("Base.Tshirt_Profession_RangerGreen","DisplayName","Park Ranger - Green");
TweakItem("Base.Tshirt_Profession_PoliceBlue","DisplayName","Police - Blue");
TweakItem("Base.Tshirt_Profession_PoliceWhite","DisplayName","Police - White");
TweakItem("Base.Tshirt_PoliceGrey","DisplayName","Police - Deputy Grey");
TweakItem("Base.Tshirt_PoliceBlue","DisplayName","Police - Trooper Blue");
TweakItem("Base.Tshirt_Profession_VeterenGreen","DisplayName","Veteran - Green");
TweakItem("Base.Tshirt_Profession_VeterenRed","DisplayName","Veteran - Red");
