require("ItemTweaker_Copy_ogsn");
-- TweakItem("Module.ItemName","AttributeName","New Attribute Value");

-- Some of these aren't necessary but I will do them all anyway
TweakItem("Base.Shorts_ShortFormal","DisplayName","Shorts");
TweakItem("Base.Trousers_WhiteTEXTURE","DisplayName","Pants");
TweakItem("Base.Trousers_WhiteTINT","DisplayName","Pants");
TweakItem("Base.Trousers_Denim","DisplayName","Jeans");
TweakItem("Base.Trousers_JeanBaggy","DisplayName","Jeans - Baggy");
TweakItem("Base.TrousersMesh_DenimLight","DisplayName","Jeans - Denim");
TweakItem("Base.Trousers_ArmyService","DisplayName","Military Uniform - Army Dress");
TweakItem("Base.Trousers_CamoDesert","DisplayName","Military Uniform - Army Camo Desert");
TweakItem("Base.Trousers_CamoGreen","DisplayName","Military Uniform - Army Camo Forest");
TweakItem("Base.Trousers_CamoUrban","DisplayName","Military Uniform - Army Camo Urban");
TweakItem("Base.Trousers_NavyBlue","DisplayName","Military Uniform - Navy");
TweakItem("Base.Dungarees","DisplayName","Overalls");
TweakItem("Base.Trousers_Chef","DisplayName","Pants - Chef");
TweakItem("Base.Trousers_Fireman","DisplayName","Pants - Firefighter");
TweakItem("Base.Trousers_Ranger","DisplayName","Pants - Park Ranger");
TweakItem("Base.Trousers_PoliceGrey","DisplayName"," Pants - Police Deputy");
TweakItem("Base.Trousers_Police","DisplayName","Pants - Police Trooper");
TweakItem("Base.Trousers_PrisonGuard","DisplayName","Pants - Prison Guard");
TweakItem("Base.Trousers_Santa","DisplayName","Pants - Santa Suit Red");
TweakItem("Base.Trousers_SantaGReen","DisplayName","Pants - Santa Suit Green");
TweakItem("Base.Trousers_Scrubs","DisplayName","Pants - Medical Scrubs");
TweakItem("Base.Trousers_Suit","DisplayName","Pants - Suit");
TweakItem("Base.Trousers_SuitTEXTURE","DisplayName","Pants - Suit");
TweakItem("Base.Trousers_SuitWhite","DisplayName","Pants - Suit");
TweakItem("Base.Trousers_Padded","DisplayName","Pants - Winter");
TweakItem("Base.Shorts_CamoGreenLong","DisplayName","Shorts - Army Camo");
TweakItem("Base.Shorts_ShortDenim","DisplayName","Shorts - Denim");
TweakItem("Base.Shorts_LongDenim","DisplayName"," Shorts - Denim Long");
TweakItem("Base.Shorts_ShortSport","DisplayName","Shorts - Sport");
TweakItem("Base.Shorts_LongSport","DisplayName"," Shorts - Sport Long");
TweakItem("Base.Shorts_LongSport_Red","DisplayName"," Shorts - Sport Long Red");
TweakItem("Base.Trousers","DisplayName","Trousers");
TweakItem("Base.Trousers_Black","DisplayName","Trousers - Black");
