require("ItemTweaker_Copy_ogsn");
-- Some of these aren't necessary but I will do them all anyway
TweakItem("Base.Hat_Bandana","WeaponSprite","Bandana");
TweakItem("Base.Hat_BandanaTied","WeaponSprite","Bandana (Rambo)");
TweakItem("Base.Hat_BandanaTINT","WeaponSprite","Bandana - Plain");
TweakItem("Base.Hat_BandanaTiedTINT","WeaponSprite","Bandana - Plain (Rambo)");
TweakItem("Base.Hat_BaseballCap","WeaponSprite","Baseball Cap");
TweakItem("Base.Hat_BaseballCap_Reverse","WeaponSprite","Baseball Cap");
TweakItem("Base.Hat_BaseballCapBlue","WeaponSprite","Baseball Cap");
TweakItem("Base.Hat_BaseballCapBlue_Reverse","WeaponSprite","Baseball Cap");
TweakItem("Base.Hat_BaseballCapRed","WeaponSprite","Baseball Cap");
TweakItem("Base.Hat_BaseballCapRed_Reverse","WeaponSprite","Baseball Cap");
TweakItem("Base.Hat_BaseballCapGreen","WeaponSprite","Baseball Cap");
TweakItem("Base.Hat_BaseballCapGreen_Reverse","WeaponSprite","Baseball Cap");
TweakItem("Base.Hat_BaseballCapArmy,","WeaponSprite","Baseball Cap Army");
TweakItem("Base.Hat_BaseballCapArmy_Reverse,","WeaponSprite","Baseball Cap Army");
TweakItem("Base.Hat_BaseballCapKY","WeaponSprite","Baseball Cap KY");
TweakItem("Base.Hat_BaseballCapKY_Reverse","WeaponSprite","Baseball Cap KY");
TweakItem("Base.Hat_BaseballCapKY_Red","WeaponSprite","Baseball Cap KY");
TweakItem("Base.Hat_Beany","WeaponSprite","Beanie");
TweakItem("Base.Hat_Beret","WeaponSprite","Beret");
TweakItem("Base.Hat_BeretArmy","WeaponSprite","Beret - Army");
TweakItem("Base.Hat_BonnieHat_CamoGreen","WeaponSprite","Bonnie Hat Camo");
TweakItem("Base.Hat_BonnieHat","WeaponSprite","Bonnie Hat Green");
TweakItem("Base.Hat_ChefHat","WeaponSprite","Chef Hat");
TweakItem("Base.Hat_Cowboy","WeaponSprite","Cowboy Hat");
TweakItem("Base.Hat_EarMuffs","WeaponSprite","Ear Muffs");
TweakItem("Base.Hat_EarMuff_Protectors","WeaponSprite","Ear Protectors");
TweakItem("Base.Hat_Fedora","WeaponSprite","Fedora");
TweakItem("Base.Hat_Fedora_Delmonte","WeaponSprite","Fedora - Black Band");
TweakItem("Base.Hat_Ranger","WeaponSprite","Flat Hat - Park Ranger");
TweakItem("Base.Hat_Police_Grey","WeaponSprite","Flat Hat - Police Deputy");
TweakItem("Base.Hat_Police","WeaponSprite","Flat Hat - Police Trooper");
TweakItem("Base.Hat_GolfHatTINT","WeaponSprite","Golf Cap");
TweakItem("Base.Hat_GolfHat","WeaponSprite","Golf Cap - Tartan");
TweakItem("Base.Hat_HardHat","WeaponSprite","Hard Hat");
TweakItem("Base.Hat_HardHat_Miner","WeaponSprite","Hard Hat - Mining");
TweakItem("Base.Hat_Army","WeaponSprite","Helmet - Army");
TweakItem("Base.Hat_BaseballHelmet_KY","WeaponSprite","Helmet - Baseball Kentucky");
TweakItem("Base.Hat_BaseballHelmet_Rangers","WeaponSprite","Helmet - Baseball Riverside Rangers");
TweakItem("Base.Hat_BaseballHelmet_Z","WeaponSprite","Helmet - Baseball Z Hurricanes");
TweakItem("Base.Hat_BicycleHelmet","WeaponSprite","Helmet - Bicycle");
TweakItem("Base.Hat_CrashHelmet","WeaponSprite","Helmet - Crash");
TweakItem("Base.Hat_CrashHelmet_Police","WeaponSprite","Helmet - Crash Police");
TweakItem("Base.Hat_CrashHelmet_Stars","WeaponSprite","Helmet - Crash USA");
TweakItem("Base.Hat_Fireman","WeaponSprite","Helmet - Firefighter");
TweakItem("Base.Hat_HockeyHelmet","WeaponSprite","Helmet - Hockey");
TweakItem("Base.Hat_JockeyHelmet01","WeaponSprite","Helmet - Jockey #1");
TweakItem("Base.Hat_JockeyHelmet02","WeaponSprite","Helmet - Jockey #2");
TweakItem("Base.Hat_JockeyHelmet03","WeaponSprite","Helmet - Jockey #3");
TweakItem("Base.Hat_JockeyHelmet04","WeaponSprite","Helmet - Jockey #4");
TweakItem("Base.Hat_JockeyHelmet05","WeaponSprite","Helmet - Jockey #5");
TweakItem("Base.Hat_JockeyHelmet06","WeaponSprite","Helmet - Jockey #6");
TweakItem("Base.Hat_RidingHelmet","WeaponSprite","Helmet - Riding");
TweakItem("Base.Hat_PartyHat_TINT","WeaponSprite","Party Hat");
TweakItem("Base.Hat_PeakedCapArmy","WeaponSprite","Peaked Cap - Army");
TweakItem("Base.Hat_Raccoon","WeaponSprite","Raccoon Skin Hat");
TweakItem("Base.Hat_FastFood","WeaponSprite","Server Hat - Fast Food");
TweakItem("Base.Hat_FastFood_IceCream","WeaponSprite","Server Hat - Ice Cream");
TweakItem("Base.Hat_FastFood_Spiffo","WeaponSprite","Server Hat - Spiffo's");
TweakItem("Base.Hat_SantaHat","WeaponSprite","Santa Hat - Red");
TweakItem("Base.Hat_SantaHatGreen","WeaponSprite","Santa Hat - Green");
TweakItem("Base.Hat_ShowerCap","WeaponSprite","Shower Cap");
TweakItem("Base.Hat_SummerHat","WeaponSprite","Summer Hat");
TweakItem("Base.Hat_SurgicalCap_Blue","WeaponSprite","Surgical Cap - Blue");
TweakItem("Base.Hat_SurgicalCap_Green","WeaponSprite","Surgical Cap - Green");
TweakItem("Base.Hat_Sweatband","WeaponSprite","Sweatband");
TweakItem("Base.Hat_WeddingVeil","WeaponSprite","Wedding Veil");
TweakItem("Base.Hat_WinterHat","WeaponSprite","Winter Hat");
TweakItem("Base.Hat_WoolyHat","WeaponSprite","Woolly Hat");
TweakItem("Base.Hat_Visor_WhiteTINT","WeaponSprite","Visor");
TweakItem("Base.Hat_VisorBlack","WeaponSprite","Visor - Black");
TweakItem("Base.Hat_VisorRed","WeaponSprite","Visor - Red");
