require("ItemTweaker_Copy_ogsn");
-- TweakItem("Module.ItemName","AttributeName","New Attribute Value");

-- Some of these aren't necessary but I will do them all anyway
TweakItem("Base.Shorts_ShortFormal","WeaponSprite","Shorts");
TweakItem("Base.Trousers_WhiteTEXTURE","WeaponSprite","Pants");
TweakItem("Base.Trousers_WhiteTINT","WeaponSprite","Pants");
TweakItem("Base.Trousers_Denim","WeaponSprite","Jeans");
TweakItem("Base.Trousers_JeanBaggy","WeaponSprite","Jeans - Baggy");
TweakItem("Base.TrousersMesh_DenimLight","WeaponSprite","Jeans - Denim");
TweakItem("Base.Trousers_ArmyService","WeaponSprite","Military Uniform - Army Dress");
TweakItem("Base.Trousers_CamoDesert","WeaponSprite","Military Uniform - Army Camo Desert");
TweakItem("Base.Trousers_CamoGreen","WeaponSprite","Military Uniform - Army Camo Forest");
TweakItem("Base.Trousers_CamoUrban","WeaponSprite","Military Uniform - Army Camo Urban");
TweakItem("Base.Trousers_NavyBlue","WeaponSprite","Military Uniform - Navy");
TweakItem("Base.Dungarees","WeaponSprite","Overalls");
TweakItem("Base.Trousers_Chef","WeaponSprite","Pants - Chef");
TweakItem("Base.Trousers_Fireman","WeaponSprite","Pants - Firefighter");
TweakItem("Base.Trousers_Ranger","WeaponSprite","Pants - Park Ranger");
TweakItem("Base.Trousers_PoliceGrey","WeaponSprite"," Pants - Police Deputy");
TweakItem("Base.Trousers_Police","WeaponSprite","Pants - Police Trooper");
TweakItem("Base.Trousers_PrisonGuard","WeaponSprite","Pants - Prison Guard");
TweakItem("Base.Trousers_Santa","WeaponSprite","Pants - Santa Suit Red");
TweakItem("Base.Trousers_SantaGReen","WeaponSprite","Pants - Santa Suit Green");
TweakItem("Base.Trousers_Scrubs","WeaponSprite","Pants - Medical Scrubs");
TweakItem("Base.Trousers_Suit","WeaponSprite","Pants - Suit");
TweakItem("Base.Trousers_SuitTEXTURE","WeaponSprite","Pants - Suit");
TweakItem("Base.Trousers_SuitWhite","WeaponSprite","Pants - Suit");
TweakItem("Base.Trousers_Padded","WeaponSprite","Pants - Winter");
TweakItem("Base.Shorts_CamoGreenLong","WeaponSprite","Shorts - Army Camo Forest");
TweakItem("Base.Shorts_CamoUrbanLong","WeaponSprite","Shorts - Army Camo Urban");
TweakItem("Base.Shorts_ShortDenim","WeaponSprite","Shorts - Denim");
TweakItem("Base.Shorts_LongDenim","WeaponSprite"," Shorts - Denim Long");
TweakItem("Base.Shorts_ShortSport","WeaponSprite","Shorts - Sport");
TweakItem("Base.Shorts_LongSport","WeaponSprite"," Shorts - Sport Long");
TweakItem("Base.Shorts_LongSport_Red","WeaponSprite"," Shorts - Sport Long Red");
TweakItem("Base.Trousers","WeaponSprite","Trousers");
TweakItem("Base.Trousers_Black","WeaponSprite","Trousers - Black");
