require("ItemTweaker_Copy_ogsn");
-- TweakItem("Module.ItemName","AttributeName","New Attribute Value");

-- Some of these aren't necessary but I will do them all anyway
TweakItem("Base.Tshirt_DefaultTEXTURE","WeaponSprite","Plain T-Shirt");
TweakItem("Base.Tshirt_DefaultTEXTURE_TINT","WeaponSprite","Plain T-Shirt");
TweakItem("Base.Tshirt_WhiteTINT","WeaponSprite","Plain T-Shirt");
TweakItem("Base.Tshirt_WhiteLongSleeve","WeaponSprite","Plain Long Sleeve T-Shirt");
TweakItem("Base.Tshirt_WhiteLongSleeveTINT","WeaponSprite","Plain Long Sleeve T-Shirt");
TweakItem("Base.Tshirt_PoloStripedTINT","WeaponSprite","Striped T-Shirt");
TweakItem("Base.Tshirt_PoloTINT","WeaponSprite","Polo T-Shirt");
TweakItem("Base.Tshirt_DefaultDECAL","WeaponSprite","Random Decal T-Shirt");
TweakItem("Base.Tshirt_DefaultDECAL_TINT","WeaponSprite","Random Decal T-Shirt");
TweakItem("Base.Tshirt_SportDECAL","WeaponSprite","Random Decal - Sport T-Shirt");
TweakItem("Base.Tshirt_Rock","WeaponSprite","Rock T-Shirt");
TweakItem("Base.Tshirt_Sport","WeaponSprite","Sport T-Shirt");
TweakItem("Base.Tshirt_ArmyGreen","WeaponSprite","Army T-Shirt");
TweakItem("Base.Tshirt_CamoDesert","WeaponSprite","Army Camo Desert T-Shirt");
TweakItem("Base.Tshirt_CamoGreen","WeaponSprite","Army Camo Forest T-Shirt");
TweakItem("Base.Tshirt_CamoUrban","WeaponSprite","Army Camo Urban T-Shirt");
TweakItem("Base.Tshirt_Fossoil","WeaponSprite","Fossoil T-Shirt");
TweakItem("Base.Tshirt_Gas2Go","WeaponSprite","Gas2Go T-Shirt");
TweakItem("Base.Tshirt_McCoys","WeaponSprite","McCoys T-Shirt");
TweakItem("Base.Tshirt_PileOCrepe","WeaponSprite","PileOCrepe T-Shirt");
TweakItem("Base.Tshirt_PizzaWhirled","WeaponSprite","Pizza Whirled T-Shirt");
TweakItem("Base.Tshirt_BusinessSpiffo","WeaponSprite","Spiffo Business T-Shirt");
TweakItem("Base.Tshirt_SpiffoDECAL","WeaponSprite","Spiffo Decal T-Shirt");
TweakItem("Base.Tshirt_ThunderGas","WeaponSprite","ThunderGas T-Shirt");
TweakItem("Base.Tshirt_ValleyStation","WeaponSprite","Valley Station T-Shirt");
TweakItem("Base.Tshirt_IndieStoneDECAL","WeaponSprite","The Indie Stone T-Shirt");
TweakItem("Base.Tshirt_Profession_FiremanBlue","WeaponSprite","Fireman - Blue T-Shirt");
TweakItem("Base.Tshirt_Profession_FiremanRed02","WeaponSprite","Fireman - Dark Red T-Shirt");
TweakItem("Base.Tshirt_Profession_FiremanRed","WeaponSprite","Fireman - Light Red T-Shirt");
TweakItem("Base.Tshirt_Profession_FiremanWhite","WeaponSprite","Fireman - White T-Shirt");
TweakItem("Base.Tshirt_Scrubs","WeaponSprite","Medical T-Shirt");
TweakItem("Base.Tshirt_Ranger","WeaponSprite","Park Ranger T-Shirt");
TweakItem("Base.Tshirt_Profession_RangerBrown","WeaponSprite","Park Ranger - Brown T-Shirt");
TweakItem("Base.Tshirt_Profession_RangerGreen","WeaponSprite","Park Ranger - Green T-Shirt");
TweakItem("Base.Tshirt_Profession_PoliceBlue","WeaponSprite","Police - Blue T-Shirt");
TweakItem("Base.Tshirt_Profession_PoliceWhite","WeaponSprite","Police - White T-Shirt");
TweakItem("Base.Tshirt_PoliceGrey","WeaponSprite","Police - Deputy Grey T-Shirt");
TweakItem("Base.Tshirt_PoliceBlue","WeaponSprite","Police - Trooper Blue T-Shirt");
TweakItem("Base.Tshirt_Profession_VeterenGreen","WeaponSprite","Veteran - Green T-Shirt");
TweakItem("Base.Tshirt_Profession_VeterenRed","WeaponSprite","Veteran - Red T-Shirt");
