require 'Items/Distributions'
require 'Items/ProceduralDistributions'
SuburbsDistributions = SuburbsDistributions or {}
ProceduralDistributions = ProceduralDistributions or {}

local function stockIWBUMS()
  -- GidOrganized.OS9pkBandages
  table.insert(ProceduralDistributions["list"]["MedicalClinicDrugs"].items, "GidOrganized.OS9pkBandages");
  table.insert(ProceduralDistributions["list"]["MedicalClinicDrugs"].items, 1);
  table.insert(ProceduralDistributions["list"]["MedicalClinicTools"].items, "GidOrganized.OS9pkBandages");
  table.insert(ProceduralDistributions["list"]["MedicalClinicTools"].items, 1);
  table.insert(ProceduralDistributions["list"]["MedicalStorageDrugs"].items, "GidOrganized.OS9pkBandages");
  table.insert(ProceduralDistributions["list"]["MedicalStorageDrugs"].items, 1);
  table.insert(ProceduralDistributions["list"]["MedicalStorageOutfit"].items, "GidOrganized.OS9pkBandages");
  table.insert(ProceduralDistributions["list"]["MedicalStorageOutfit"].items, 1);
  table.insert(ProceduralDistributions["list"]["MedicalStorageTools"].items, "GidOrganized.OS9pkBandages");
  table.insert(ProceduralDistributions["list"]["MedicalStorageTools"].items, 1);
  -- GidOrganized.OS9pkSterileBandages
  table.insert(ProceduralDistributions["list"]["MedicalClinicDrugs"].items, "GidOrganized.OS9pkSterileBandages");
  table.insert(ProceduralDistributions["list"]["MedicalClinicDrugs"].items, 1);
  table.insert(ProceduralDistributions["list"]["MedicalClinicTools"].items, "GidOrganized.OS9pkSterileBandages");
  table.insert(ProceduralDistributions["list"]["MedicalClinicTools"].items, 1);
  table.insert(ProceduralDistributions["list"]["MedicalStorageDrugs"].items, "GidOrganized.OS9pkSterileBandages");
  table.insert(ProceduralDistributions["list"]["MedicalStorageDrugs"].items, 1);
  table.insert(ProceduralDistributions["list"]["MedicalStorageOutfit"].items, "GidOrganized.OS9pkSterileBandages");
  table.insert(ProceduralDistributions["list"]["MedicalStorageOutfit"].items, 1);
  table.insert(ProceduralDistributions["list"]["MedicalStorageTools"].items, "GidOrganized.OS9pkSterileBandages");
  table.insert(ProceduralDistributions["list"]["MedicalStorageTools"].items, 1);
  -- GidOrganized.OS12pkCottonBalls
  table.insert(ProceduralDistributions["list"]["MedicalClinicDrugs"].items, "GidOrganized.OS12pkCottonBalls");
  table.insert(ProceduralDistributions["list"]["MedicalClinicDrugs"].items, 1);
  table.insert(ProceduralDistributions["list"]["MedicalClinicTools"].items, "GidOrganized.OS12pkCottonBalls");
  table.insert(ProceduralDistributions["list"]["MedicalClinicTools"].items, 1);
  table.insert(ProceduralDistributions["list"]["MedicalStorageDrugs"].items, "GidOrganized.OS12pkCottonBalls");
  table.insert(ProceduralDistributions["list"]["MedicalStorageDrugs"].items, 1);
  table.insert(ProceduralDistributions["list"]["MedicalStorageOutfit"].items, "GidOrganized.OS12pkCottonBalls");
  table.insert(ProceduralDistributions["list"]["MedicalStorageOutfit"].items, 1);
  table.insert(ProceduralDistributions["list"]["MedicalStorageTools"].items, "GidOrganized.OS12pkCottonBalls");
  table.insert(ProceduralDistributions["list"]["MedicalStorageTools"].items, 1);
  -- GidOrganized.OS50pkPainkillers
  table.insert(ProceduralDistributions["list"]["MedicalClinicDrugs"].items, "GidOrganized.OS50pkPainkillers");
  table.insert(ProceduralDistributions["list"]["MedicalClinicDrugs"].items, 1);
  table.insert(ProceduralDistributions["list"]["MedicalClinicTools"].items, "GidOrganized.OS50pkPainkillers");
  table.insert(ProceduralDistributions["list"]["MedicalClinicTools"].items, 1);
  table.insert(ProceduralDistributions["list"]["MedicalStorageDrugs"].items, "GidOrganized.OS50pkPainkillers");
  table.insert(ProceduralDistributions["list"]["MedicalStorageDrugs"].items, 1);
  table.insert(ProceduralDistributions["list"]["MedicalStorageOutfit"].items, "GidOrganized.OS50pkPainkillers");
  table.insert(ProceduralDistributions["list"]["MedicalStorageOutfit"].items, 1);
  table.insert(ProceduralDistributions["list"]["MedicalStorageTools"].items, "GidOrganized.OS50pkPainkillers");
  table.insert(ProceduralDistributions["list"]["MedicalStorageTools"].items, 1);
  -- GidOrganized.OS50pkVitamins
  table.insert(ProceduralDistributions["list"]["MedicalClinicDrugs"].items, "GidOrganized.OS50pkVitamins");
  table.insert(ProceduralDistributions["list"]["MedicalClinicDrugs"].items, 1);
  table.insert(ProceduralDistributions["list"]["MedicalClinicTools"].items, "GidOrganized.OS50pkVitamins");
  table.insert(ProceduralDistributions["list"]["MedicalClinicTools"].items, 1);
  table.insert(ProceduralDistributions["list"]["MedicalStorageDrugs"].items, "GidOrganized.OS50pkVitamins");
  table.insert(ProceduralDistributions["list"]["MedicalStorageDrugs"].items, 1);
  table.insert(ProceduralDistributions["list"]["MedicalStorageOutfit"].items, "GidOrganized.OS50pkVitamins");
  table.insert(ProceduralDistributions["list"]["MedicalStorageOutfit"].items, 1);
  table.insert(ProceduralDistributions["list"]["MedicalStorageTools"].items, "GidOrganized.OS50pkVitamins");
  table.insert(ProceduralDistributions["list"]["MedicalStorageTools"].items, 1);
  -- GidOrganized.OS50pkBetaBlockers
  table.insert(ProceduralDistributions["list"]["MedicalClinicDrugs"].items, "GidOrganized.OS50pkBetaBlockers");
  table.insert(ProceduralDistributions["list"]["MedicalClinicDrugs"].items, 1);
  table.insert(ProceduralDistributions["list"]["MedicalClinicTools"].items, "GidOrganized.OS50pkBetaBlockers");
  table.insert(ProceduralDistributions["list"]["MedicalClinicTools"].items, 1);
  table.insert(ProceduralDistributions["list"]["MedicalStorageDrugs"].items, "GidOrganized.OS50pkBetaBlockers");
  table.insert(ProceduralDistributions["list"]["MedicalStorageDrugs"].items, 1);
  table.insert(ProceduralDistributions["list"]["MedicalStorageOutfit"].items, "GidOrganized.OS50pkBetaBlockers");
  table.insert(ProceduralDistributions["list"]["MedicalStorageOutfit"].items, 1);
  table.insert(ProceduralDistributions["list"]["MedicalStorageTools"].items, "GidOrganized.OS50pkBetaBlockers");
  table.insert(ProceduralDistributions["list"]["MedicalStorageTools"].items, 1);
  -- GidOrganized.OS50pkAntidepressants
  table.insert(ProceduralDistributions["list"]["MedicalClinicDrugs"].items, "GidOrganized.OS50pkAntidepressants");
  table.insert(ProceduralDistributions["list"]["MedicalClinicDrugs"].items, 1);
  table.insert(ProceduralDistributions["list"]["MedicalClinicTools"].items, "GidOrganized.OS50pkAntidepressants");
  table.insert(ProceduralDistributions["list"]["MedicalClinicTools"].items, 1);
  table.insert(ProceduralDistributions["list"]["MedicalStorageDrugs"].items, "GidOrganized.OS50pkAntidepressants");
  table.insert(ProceduralDistributions["list"]["MedicalStorageDrugs"].items, 1);
  table.insert(ProceduralDistributions["list"]["MedicalStorageOutfit"].items, "GidOrganized.OS50pkAntidepressants");
  table.insert(ProceduralDistributions["list"]["MedicalStorageOutfit"].items, 1);
  table.insert(ProceduralDistributions["list"]["MedicalStorageTools"].items, "GidOrganized.OS50pkAntidepressants");
  table.insert(ProceduralDistributions["list"]["MedicalStorageTools"].items, 1);
  -- GidOrganized.OS50pkSleepingPills
  table.insert(ProceduralDistributions["list"]["MedicalClinicDrugs"].items, "GidOrganized.OS50pkSleepingPills");
  table.insert(ProceduralDistributions["list"]["MedicalClinicDrugs"].items, 1);
  table.insert(ProceduralDistributions["list"]["MedicalClinicTools"].items, "GidOrganized.OS50pkSleepingPills");
  table.insert(ProceduralDistributions["list"]["MedicalClinicTools"].items, 1);
  table.insert(ProceduralDistributions["list"]["MedicalStorageDrugs"].items, "GidOrganized.OS50pkSleepingPills");
  table.insert(ProceduralDistributions["list"]["MedicalStorageDrugs"].items, 1);
  table.insert(ProceduralDistributions["list"]["MedicalStorageOutfit"].items, "GidOrganized.OS50pkSleepingPills");
  table.insert(ProceduralDistributions["list"]["MedicalStorageOutfit"].items, 1);
  table.insert(ProceduralDistributions["list"]["MedicalStorageTools"].items, "GidOrganized.OS50pkSleepingPills");
  table.insert(ProceduralDistributions["list"]["MedicalStorageTools"].items, 1);
  -- GidOrganized.OS4pkDisinfectant
  table.insert(ProceduralDistributions["list"]["MedicalClinicDrugs"].items, "GidOrganized.OS4pkDisinfectant");
  table.insert(ProceduralDistributions["list"]["MedicalClinicDrugs"].items, 1);
  table.insert(ProceduralDistributions["list"]["MedicalClinicTools"].items, "GidOrganized.OS4pkDisinfectant");
  table.insert(ProceduralDistributions["list"]["MedicalClinicTools"].items, 1);
  table.insert(ProceduralDistributions["list"]["MedicalStorageDrugs"].items, "GidOrganized.OS4pkDisinfectant");
  table.insert(ProceduralDistributions["list"]["MedicalStorageDrugs"].items, 1);
  table.insert(ProceduralDistributions["list"]["MedicalStorageOutfit"].items, "GidOrganized.OS4pkDisinfectant");
  table.insert(ProceduralDistributions["list"]["MedicalStorageOutfit"].items, 1);
  table.insert(ProceduralDistributions["list"]["MedicalStorageTools"].items, "GidOrganized.OS4pkDisinfectant");
  table.insert(ProceduralDistributions["list"]["MedicalStorageTools"].items, 1);
  -- GidOrganized.OS30pkAlcoholWipes
  table.insert(ProceduralDistributions["list"]["MedicalClinicDrugs"].items, "GidOrganized.OS30pkAlcoholWipes");
  table.insert(ProceduralDistributions["list"]["MedicalClinicDrugs"].items, 1);
  table.insert(ProceduralDistributions["list"]["MedicalClinicTools"].items, "GidOrganized.OS30pkAlcoholWipes");
  table.insert(ProceduralDistributions["list"]["MedicalClinicTools"].items, 1);
  table.insert(ProceduralDistributions["list"]["MedicalStorageDrugs"].items, "GidOrganized.OS30pkAlcoholWipes");
  table.insert(ProceduralDistributions["list"]["MedicalStorageDrugs"].items, 1);
  table.insert(ProceduralDistributions["list"]["MedicalStorageOutfit"].items, "GidOrganized.OS30pkAlcoholWipes");
  table.insert(ProceduralDistributions["list"]["MedicalStorageOutfit"].items, 1);
  table.insert(ProceduralDistributions["list"]["MedicalStorageTools"].items, "GidOrganized.OS30pkAlcoholWipes");
  table.insert(ProceduralDistributions["list"]["MedicalStorageTools"].items, 1);
  -- GidOrganized.OS30pkAntibiotics
  table.insert(ProceduralDistributions["list"]["MedicalClinicDrugs"].items, "GidOrganized.OS30pkAntibiotics");
  table.insert(ProceduralDistributions["list"]["MedicalClinicDrugs"].items, 1);
  table.insert(ProceduralDistributions["list"]["MedicalClinicTools"].items, "GidOrganized.OS30pkAntibiotics");
  table.insert(ProceduralDistributions["list"]["MedicalClinicTools"].items, 1);
  table.insert(ProceduralDistributions["list"]["MedicalStorageDrugs"].items, "GidOrganized.OS30pkAntibiotics");
  table.insert(ProceduralDistributions["list"]["MedicalStorageDrugs"].items, 1);
  table.insert(ProceduralDistributions["list"]["MedicalStorageOutfit"].items, "GidOrganized.OS30pkAntibiotics");
  table.insert(ProceduralDistributions["list"]["MedicalStorageOutfit"].items, 1);
  table.insert(ProceduralDistributions["list"]["MedicalStorageTools"].items, "GidOrganized.OS30pkAntibiotics");
  table.insert(ProceduralDistributions["list"]["MedicalStorageTools"].items, 1);
  -- GidOrganized.OS12pkAdhesiveBandages
  table.insert(ProceduralDistributions["list"]["MedicalClinicDrugs"].items, "GidOrganized.OS12pkAdhesiveBandages");
  table.insert(ProceduralDistributions["list"]["MedicalClinicDrugs"].items, 1);
  table.insert(ProceduralDistributions["list"]["MedicalClinicTools"].items, "GidOrganized.OS12pkAdhesiveBandages");
  table.insert(ProceduralDistributions["list"]["MedicalClinicTools"].items, 1);
  table.insert(ProceduralDistributions["list"]["MedicalStorageDrugs"].items, "GidOrganized.OS12pkAdhesiveBandages");
  table.insert(ProceduralDistributions["list"]["MedicalStorageDrugs"].items, 1);
  table.insert(ProceduralDistributions["list"]["MedicalStorageOutfit"].items, "GidOrganized.OS12pkAdhesiveBandages");
  table.insert(ProceduralDistributions["list"]["MedicalStorageOutfit"].items, 1);
  table.insert(ProceduralDistributions["list"]["MedicalStorageTools"].items, "GidOrganized.OS12pkAdhesiveBandages");
  table.insert(ProceduralDistributions["list"]["MedicalStorageTools"].items, 1);
  -- GidOrganizedFood.OS4pkDuctTape
  table.insert(ProceduralDistributions["list"]["ToolStoreCarpentry"].items, "GidOrganizedFood.OS4pkDuctTape");
  table.insert(ProceduralDistributions["list"]["ToolStoreCarpentry"].items, 1);
  table.insert(ProceduralDistributions["list"]["ToolStoreMisc"].items, "GidOrganizedFood.OS4pkDuctTape");
  table.insert(ProceduralDistributions["list"]["ToolStoreMisc"].items, 1);
  table.insert(ProceduralDistributions["list"]["ArmyHangarTools"].items, "GidOrganizedFood.OS4pkDuctTape");
  table.insert(ProceduralDistributions["list"]["ArmyHangarTools"].items, 1);
  table.insert(ProceduralDistributions["list"]["CrateCarpentry"].items, "GidOrganizedFood.OS4pkDuctTape");
  table.insert(ProceduralDistributions["list"]["CrateCarpentry"].items, 1);
  table.insert(ProceduralDistributions["list"]["GarageCarpentry"].items, "GidOrganizedFood.OS4pkDuctTape");
  table.insert(ProceduralDistributions["list"]["GarageCarpentry"].items, 1);
  table.insert(ProceduralDistributions["list"]["JanitorTools"].items, "GidOrganizedFood.OS4pkDuctTape");
  table.insert(ProceduralDistributions["list"]["JanitorTools"].items, 1);
  -- GidOrganizedFood.OS6pkCannedSoup
  table.insert(ProceduralDistributions["list"]["CrateCannedFood"].items, "GidOrganizedFood.OS6pkCannedSoup");
  table.insert(ProceduralDistributions["list"]["CrateCannedFood"].items, 1);
  table.insert(ProceduralDistributions["list"]["GigamartCannedFood"].items, "GidOrganizedFood.OS6pkCannedSoup");
  table.insert(ProceduralDistributions["list"]["GigamartCannedFood"].items, 1);
  -- GidOrganizedFood.OS6pkCannedBeans
  table.insert(ProceduralDistributions["list"]["CrateCannedFood"].items, "GidOrganizedFood.OS6pkCannedBeans");
  table.insert(ProceduralDistributions["list"]["CrateCannedFood"].items, 1);
  table.insert(ProceduralDistributions["list"]["GigamartCannedFood"].items, "GidOrganizedFood.OS6pkCannedBeans");
  table.insert(ProceduralDistributions["list"]["GigamartCannedFood"].items, 1);
  -- GidOrganizedFood.OS6pkCannedBolognese
  table.insert(ProceduralDistributions["list"]["CrateCannedFood"].items, "GidOrganizedFood.OS6pkCannedBolognese");
  table.insert(ProceduralDistributions["list"]["CrateCannedFood"].items, 1);
  table.insert(ProceduralDistributions["list"]["GigamartCannedFood"].items, "GidOrganizedFood.OS6pkCannedBolognese");
  table.insert(ProceduralDistributions["list"]["GigamartCannedFood"].items, 1);
  -- GidOrganizedFood.OS6pkCannedCarrots
  table.insert(ProceduralDistributions["list"]["CrateCannedFood"].items, "GidOrganizedFood.OS6pkCannedCarrots");
  table.insert(ProceduralDistributions["list"]["CrateCannedFood"].items, 1);
  table.insert(ProceduralDistributions["list"]["GigamartCannedFood"].items, "GidOrganizedFood.OS6pkCannedCarrots");
  table.insert(ProceduralDistributions["list"]["GigamartCannedFood"].items, 1);
  -- GidOrganizedFood.OS6pkCannedChili
  table.insert(ProceduralDistributions["list"]["CrateCannedFood"].items, "GidOrganizedFood.OS6pkCannedChili");
  table.insert(ProceduralDistributions["list"]["CrateCannedFood"].items, 1);
  table.insert(ProceduralDistributions["list"]["GigamartCannedFood"].items, "GidOrganizedFood.OS6pkCannedChili");
  table.insert(ProceduralDistributions["list"]["GigamartCannedFood"].items, 1);
  -- GidOrganizedFood.OS6pkCannedCorn
  table.insert(ProceduralDistributions["list"]["CrateCannedFood"].items, "GidOrganizedFood.OS6pkCannedCorn");
  table.insert(ProceduralDistributions["list"]["CrateCannedFood"].items, 1);
  table.insert(ProceduralDistributions["list"]["GigamartCannedFood"].items, "GidOrganizedFood.OS6pkCannedCorn");
  table.insert(ProceduralDistributions["list"]["GigamartCannedFood"].items, 1);
  -- GidOrganizedFood.OS6pkCannedCornedBeef
  table.insert(ProceduralDistributions["list"]["CrateCannedFood"].items, "GidOrganizedFood.OS6pkCannedCornedBeef");
  table.insert(ProceduralDistributions["list"]["CrateCannedFood"].items, 1);
  table.insert(ProceduralDistributions["list"]["GigamartCannedFood"].items, "GidOrganizedFood.OS6pkCannedCornedBeef");
  table.insert(ProceduralDistributions["list"]["GigamartCannedFood"].items, 1);
  -- GidOrganizedFood.OS6pkCannedMushSoup
  table.insert(ProceduralDistributions["list"]["CrateCannedFood"].items, "GidOrganizedFood.OS6pkCannedMushSoup");
  table.insert(ProceduralDistributions["list"]["CrateCannedFood"].items, 1);
  table.insert(ProceduralDistributions["list"]["GigamartCannedFood"].items, "GidOrganizedFood.OS6pkCannedMushSoup");
  table.insert(ProceduralDistributions["list"]["GigamartCannedFood"].items, 1);
  -- GidOrganizedFood.OS6pkCannedPeas
  table.insert(ProceduralDistributions["list"]["CrateCannedFood"].items, "GidOrganizedFood.OS6pkCannedPeas");
  table.insert(ProceduralDistributions["list"]["CrateCannedFood"].items, 1);
  table.insert(ProceduralDistributions["list"]["GigamartCannedFood"].items, "GidOrganizedFood.OS6pkCannedPeas");
  table.insert(ProceduralDistributions["list"]["GigamartCannedFood"].items, 1);
  -- GidOrganizedFood.OS6pkCannedPotato
  table.insert(ProceduralDistributions["list"]["CrateCannedFood"].items, "GidOrganizedFood.OS6pkCannedPotato");
  table.insert(ProceduralDistributions["list"]["CrateCannedFood"].items, 1);
  table.insert(ProceduralDistributions["list"]["GigamartCannedFood"].items, "GidOrganizedFood.OS6pkCannedPotato");
  table.insert(ProceduralDistributions["list"]["GigamartCannedFood"].items, 1);
  -- GidOrganizedFood.OS6pkCannedTomato
  table.insert(ProceduralDistributions["list"]["CrateCannedFood"].items, "GidOrganizedFood.OS6pkCannedTomato");
  table.insert(ProceduralDistributions["list"]["CrateCannedFood"].items, 1);
  table.insert(ProceduralDistributions["list"]["GigamartCannedFood"].items, "GidOrganizedFood.OS6pkCannedTomato");
  table.insert(ProceduralDistributions["list"]["GigamartCannedFood"].items, 1);
  -- GidOrganizedFood.OS4pkSardines
  table.insert(ProceduralDistributions["list"]["CrateCannedFood"].items, "GidOrganizedFood.OS4pkSardines");
  table.insert(ProceduralDistributions["list"]["CrateCannedFood"].items, 1);
  table.insert(ProceduralDistributions["list"]["GigamartCannedFood"].items, "GidOrganizedFood.OS4pkSardines");
  table.insert(ProceduralDistributions["list"]["GigamartCannedFood"].items, 1);
  -- GidOrganizedFood.OS8pkCannedTuna
  table.insert(ProceduralDistributions["list"]["CrateCannedFood"].items, "GidOrganizedFood.OS8pkCannedTuna");
  table.insert(ProceduralDistributions["list"]["CrateCannedFood"].items, 1);
  table.insert(ProceduralDistributions["list"]["GigamartCannedFood"].items, "GidOrganizedFood.OS8pkCannedTuna");
  table.insert(ProceduralDistributions["list"]["GigamartCannedFood"].items, 1);
  -- GidOrganizedFood.OS4pkCoffee
  table.insert(ProceduralDistributions["list"]["GigamartDryGoods"].items, "GidOrganizedFood.OS4pkCoffee");
  table.insert(ProceduralDistributions["list"]["GigamartDryGoods"].items, 1);
  table.insert(ProceduralDistributions["list"]["StoreKitchenCafe"].items, "GidOrganizedFood.OS4pkCoffee");
  table.insert(ProceduralDistributions["list"]["StoreKitchenCafe"].items, 1);
  table.insert(ProceduralDistributions["list"]["BreakRoomShelves"].items, "GidOrganizedFood.OS4pkCoffee");
  table.insert(ProceduralDistributions["list"]["BreakRoomShelves"].items, 1);
  table.insert(ProceduralDistributions["list"]["BreakRoomCounter"].items, "GidOrganizedFood.OS4pkCoffee");
  table.insert(ProceduralDistributions["list"]["BreakRoomCounter"].items, 1);
  -- GidOrganizedFood.OS24pkWaterBottleFull
  table.insert(ProceduralDistributions["list"]["GigamartBottles"].items, "GidOrganizedFood.OS24pkWaterBottleFull");
  table.insert(ProceduralDistributions["list"]["GigamartBottles"].items, 1);
  table.insert(ProceduralDistributions["list"]["KitchenBottles"].items, "GidOrganizedFood.OS24pkWaterBottleFull");
  table.insert(ProceduralDistributions["list"]["KitchenBottles"].items, 1);
  -- GidOrganizedFood.OS6pkPopDiet
  table.insert(ProceduralDistributions["list"]["GigamartBottles"].items, "GidOrganizedFood.OS6pkPopDiet");
  table.insert(ProceduralDistributions["list"]["GigamartBottles"].items, 1);
  table.insert(ProceduralDistributions["list"]["KitchenBottles"].items, "GidOrganizedFood.OS6pkPopDiet");
  table.insert(ProceduralDistributions["list"]["KitchenBottles"].items, 1);
  -- GidOrganizedFood.OS6pkPop
  table.insert(ProceduralDistributions["list"]["GigamartBottles"].items, "GidOrganizedFood.OS6pkPop");
  table.insert(ProceduralDistributions["list"]["GigamartBottles"].items, 1);
  table.insert(ProceduralDistributions["list"]["KitchenBottles"].items, "GidOrganizedFood.OS6pkPop");
  table.insert(ProceduralDistributions["list"]["KitchenBottles"].items, 1);
  -- GidOrganizedFood.OS6pkFizz
  table.insert(ProceduralDistributions["list"]["GigamartBottles"].items, "GidOrganizedFood.OS6pkFizz");
  table.insert(ProceduralDistributions["list"]["GigamartBottles"].items, 1);
  table.insert(ProceduralDistributions["list"]["KitchenBottles"].items, "GidOrganizedFood.OS6pkFizz");
  table.insert(ProceduralDistributions["list"]["KitchenBottles"].items, 1);
end

local function stockClassic()
  -- Medical Packs
  table.insert(SuburbsDistributions["medicalstorage"]["counter"].items, "GidOrganized.OS12pkAdhesiveBandages");
  table.insert(SuburbsDistributions["medicalstorage"]["counter"].items, 1);
  table.insert(SuburbsDistributions["medicalstorage"]["counter"].items, "GidOrganized.OS9pkBandages");
  table.insert(SuburbsDistributions["medicalstorage"]["counter"].items, 1);
  table.insert(SuburbsDistributions["medicalstorage"]["counter"].items, "GidOrganized.OS9pkSterileBandages");
  table.insert(SuburbsDistributions["medicalstorage"]["counter"].items, 1);
  table.insert(SuburbsDistributions["medicalstorage"]["counter"].items, "GidOrganized.OS12pkCottonBalls");
  table.insert(SuburbsDistributions["medicalstorage"]["counter"].items, 1);
  table.insert(SuburbsDistributions["medicalstorage"]["counter"].items, "GidOrganized.OS50pkPainkillers");
  table.insert(SuburbsDistributions["medicalstorage"]["counter"].items, 0.5);
  table.insert(SuburbsDistributions["medicalstorage"]["counter"].items, "GidOrganized.OS50pkVitamins");
  table.insert(SuburbsDistributions["medicalstorage"]["counter"].items, 0.5);
  table.insert(SuburbsDistributions["medicalstorage"]["counter"].items, "GidOrganized.OS50pkBetaBlockers");
  table.insert(SuburbsDistributions["medicalstorage"]["counter"].items, 0.5);
  table.insert(SuburbsDistributions["medicalstorage"]["counter"].items, "GidOrganized.OS50pkAntidepressants");
  table.insert(SuburbsDistributions["medicalstorage"]["counter"].items, 0.5);
  table.insert(SuburbsDistributions["medicalstorage"]["counter"].items, "GidOrganized.OS50pkSleepingPills");
  table.insert(SuburbsDistributions["medicalstorage"]["counter"].items, 0.5);
  table.insert(SuburbsDistributions["medicalstorage"]["counter"].items, "GidOrganized.OS4pkDisinfectant");
  table.insert(SuburbsDistributions["medicalstorage"]["counter"].items, 1);
  table.insert(SuburbsDistributions["medicalstorage"]["counter"].items, "GidOrganized.OS30pkAlcoholWipes");
  table.insert(SuburbsDistributions["medicalstorage"]["counter"].items, 0.8);
  table.insert(SuburbsDistributions["medicalstorage"]["counter"].items, "GidOrganized.OS30pkAntibiotics");
  table.insert(SuburbsDistributions["medicalstorage"]["counter"].items, 0.2);
  table.insert(SuburbsDistributions["medicalstorage"]["metal_shelves"].items, "GidOrganized.OS12pkAdhesiveBandages");
  table.insert(SuburbsDistributions["medicalstorage"]["metal_shelves"].items, 1);
  table.insert(SuburbsDistributions["medicalstorage"]["metal_shelves"].items, "GidOrganized.OS9pkBandages");
  table.insert(SuburbsDistributions["medicalstorage"]["metal_shelves"].items, 1);
  table.insert(SuburbsDistributions["medicalstorage"]["metal_shelves"].items, "GidOrganized.OS9pkSterileBandages");
  table.insert(SuburbsDistributions["medicalstorage"]["metal_shelves"].items, 1);
  table.insert(SuburbsDistributions["medicalstorage"]["metal_shelves"].items, "GidOrganized.OS12pkCottonBalls");
  table.insert(SuburbsDistributions["medicalstorage"]["metal_shelves"].items, 1);
  table.insert(SuburbsDistributions["medicalstorage"]["metal_shelves"].items, "GidOrganized.OS50pkPainkillers");
  table.insert(SuburbsDistributions["medicalstorage"]["metal_shelves"].items, 0.5);
  table.insert(SuburbsDistributions["medicalstorage"]["metal_shelves"].items, "GidOrganized.OS50pkVitamins");
  table.insert(SuburbsDistributions["medicalstorage"]["metal_shelves"].items, 0.5);
  table.insert(SuburbsDistributions["medicalstorage"]["metal_shelves"].items, "GidOrganized.OS50pkBetaBlockers");
  table.insert(SuburbsDistributions["medicalstorage"]["metal_shelves"].items, 0.5);
  table.insert(SuburbsDistributions["medicalstorage"]["metal_shelves"].items, "GidOrganized.OS50pkAntidepressants");
  table.insert(SuburbsDistributions["medicalstorage"]["metal_shelves"].items, 0.5);
  table.insert(SuburbsDistributions["medicalstorage"]["metal_shelves"].items, "GidOrganized.OS50pkSleepingPills");
  table.insert(SuburbsDistributions["medicalstorage"]["metal_shelves"].items, 0.5);
  table.insert(SuburbsDistributions["medicalstorage"]["metal_shelves"].items, "GidOrganized.OS4pkDisinfectant");
  table.insert(SuburbsDistributions["medicalstorage"]["metal_shelves"].items, 1);
  table.insert(SuburbsDistributions["medicalstorage"]["metal_shelves"].items, "GidOrganized.OS30pkAlcoholWipes");
  table.insert(SuburbsDistributions["medicalstorage"]["metal_shelves"].items, 0.8);
  table.insert(SuburbsDistributions["medicalstorage"]["metal_shelves"].items, "GidOrganized.OS30pkAntibiotics");
  table.insert(SuburbsDistributions["medicalstorage"]["metal_shelves"].items, 0.2);
  table.insert(SuburbsDistributions["pharmacystorage"]["counter"].items, "GidOrganized.OS12pkAdhesiveBandages");
  table.insert(SuburbsDistributions["pharmacystorage"]["counter"].items, 1);
  table.insert(SuburbsDistributions["pharmacystorage"]["counter"].items, "GidOrganized.OS9pkBandages");
  table.insert(SuburbsDistributions["pharmacystorage"]["counter"].items, 1);
  table.insert(SuburbsDistributions["pharmacystorage"]["counter"].items, "GidOrganized.OS9pkSterileBandages");
  table.insert(SuburbsDistributions["pharmacystorage"]["counter"].items, 1);
  table.insert(SuburbsDistributions["pharmacystorage"]["counter"].items, "GidOrganized.OS50pkPainkillers");
  table.insert(SuburbsDistributions["pharmacystorage"]["counter"].items, 0.5);
  table.insert(SuburbsDistributions["pharmacystorage"]["counter"].items, "GidOrganized.OS50pkVitamins");
  table.insert(SuburbsDistributions["pharmacystorage"]["counter"].items, 0.5);
  table.insert(SuburbsDistributions["pharmacystorage"]["counter"].items, "GidOrganized.OS50pkBetaBlockers");
  table.insert(SuburbsDistributions["pharmacystorage"]["counter"].items, 0.5);
  table.insert(SuburbsDistributions["pharmacystorage"]["counter"].items, "GidOrganized.OS50pkAntidepressants");
  table.insert(SuburbsDistributions["pharmacystorage"]["counter"].items, 0.5);
  table.insert(SuburbsDistributions["pharmacystorage"]["counter"].items, "GidOrganized.OS50pkSleepingPills");
  table.insert(SuburbsDistributions["pharmacystorage"]["counter"].items, 0.5);
  table.insert(SuburbsDistributions["pharmacystorage"]["counter"].items, "GidOrganized.OS4pkDisinfectant");
  table.insert(SuburbsDistributions["pharmacystorage"]["counter"].items, 1);
  table.insert(SuburbsDistributions["pharmacystorage"]["counter"].items, "GidOrganized.OS30pkAlcoholWipes");
  table.insert(SuburbsDistributions["pharmacystorage"]["counter"].items, 0.8);
  table.insert(SuburbsDistributions["pharmacystorage"]["counter"].items, "GidOrganized.OS30pkAntibiotics");
  table.insert(SuburbsDistributions["pharmacystorage"]["counter"].items, 0.2);
  table.insert(SuburbsDistributions["medicaloffice"]["counter"].items, "GidOrganized.OS12pkAdhesiveBandages");
  table.insert(SuburbsDistributions["medicaloffice"]["counter"].items, 1);
  table.insert(SuburbsDistributions["medicaloffice"]["counter"].items, "GidOrganized.OS9pkBandages");
  table.insert(SuburbsDistributions["medicaloffice"]["counter"].items, 1);
  table.insert(SuburbsDistributions["medicaloffice"]["counter"].items, "GidOrganized.OS9pkSterileBandages");
  table.insert(SuburbsDistributions["medicaloffice"]["counter"].items, 1);
  table.insert(SuburbsDistributions["medicaloffice"]["counter"].items, "GidOrganized.OS50pkPainkillers");
  table.insert(SuburbsDistributions["medicaloffice"]["counter"].items, 0.5);
  table.insert(SuburbsDistributions["medicaloffice"]["counter"].items, "GidOrganized.OS50pkVitamins");
  table.insert(SuburbsDistributions["medicaloffice"]["counter"].items, 0.5);
  table.insert(SuburbsDistributions["medicaloffice"]["counter"].items, "GidOrganized.OS50pkBetaBlockers");
  table.insert(SuburbsDistributions["medicaloffice"]["counter"].items, 0.5);
  table.insert(SuburbsDistributions["medicaloffice"]["counter"].items, "GidOrganized.OS50pkAntidepressants");
  table.insert(SuburbsDistributions["medicaloffice"]["counter"].items, 0.5);
  table.insert(SuburbsDistributions["medicaloffice"]["counter"].items, "GidOrganized.OS50pkSleepingPills");
  table.insert(SuburbsDistributions["medicaloffice"]["counter"].items, 0.5);
  table.insert(SuburbsDistributions["medicaloffice"]["counter"].items, "GidOrganized.OS4pkDisinfectant");
  table.insert(SuburbsDistributions["medicaloffice"]["counter"].items, 1);
  table.insert(SuburbsDistributions["medicaloffice"]["counter"].items, "GidOrganized.OS30pkAlcoholWipes");
  table.insert(SuburbsDistributions["medicaloffice"]["counter"].items, 0.8);
  table.insert(SuburbsDistributions["medicaloffice"]["counter"].items, "GidOrganized.OS30pkAntibiotics");
  table.insert(SuburbsDistributions["medicaloffice"]["counter"].items, 0.2);
  -- DuctTape
  table.insert(SuburbsDistributions["shed"]["other"].items, "GidOrganizedFood.OS4pkDuctTape");
  table.insert(SuburbsDistributions["shed"]["other"].items, 1);
  table.insert(SuburbsDistributions["toolstore"]["shelves"].items, "GidOrganizedFood.OS4pkDuctTape");
  table.insert(SuburbsDistributions["toolstore"]["shelves"].items, 1);
  table.insert(SuburbsDistributions["toolstore"]["counter"].items, "GidOrganizedFood.OS4pkDuctTape");
  table.insert(SuburbsDistributions["toolstore"]["counter"].items, 1);
  -- Food Packs
  table.insert(SuburbsDistributions["generalstorestorage"]["other"].items, "GidOrganizedFood.OS6pkCannedSoup");
  table.insert(SuburbsDistributions["generalstorestorage"]["other"].items, 1);
  table.insert(SuburbsDistributions["generalstorestorage"]["other"].items, "GidOrganizedFood.OS6pkCannedBeans");
  table.insert(SuburbsDistributions["generalstorestorage"]["other"].items, 1);
  table.insert(SuburbsDistributions["generalstorestorage"]["other"].items, "GidOrganizedFood.OS6pkCannedBolognese");
  table.insert(SuburbsDistributions["generalstorestorage"]["other"].items, 1);
  table.insert(SuburbsDistributions["generalstorestorage"]["other"].items, "GidOrganizedFood.OS6pkCannedCarrots");
  table.insert(SuburbsDistributions["generalstorestorage"]["other"].items, 1);
  table.insert(SuburbsDistributions["generalstorestorage"]["other"].items, "GidOrganizedFood.OS6pkCannedChili");
  table.insert(SuburbsDistributions["generalstorestorage"]["other"].items, 1);
  table.insert(SuburbsDistributions["generalstorestorage"]["other"].items, "GidOrganizedFood.OS6pkCannedCorn");
  table.insert(SuburbsDistributions["generalstorestorage"]["other"].items, 1);
  table.insert(SuburbsDistributions["generalstorestorage"]["other"].items, "GidOrganizedFood.OS6pkCannedCornedBeef");
  table.insert(SuburbsDistributions["generalstorestorage"]["other"].items, 1);
  table.insert(SuburbsDistributions["generalstorestorage"]["other"].items, "GidOrganizedFood.OS6pkCannedMushSoup");
  table.insert(SuburbsDistributions["generalstorestorage"]["other"].items, 1);
  table.insert(SuburbsDistributions["generalstorestorage"]["other"].items, "GidOrganizedFood.OS6pkCannedPeas");
  table.insert(SuburbsDistributions["generalstorestorage"]["other"].items, 1);
  table.insert(SuburbsDistributions["generalstorestorage"]["other"].items, "GidOrganizedFood.OS6pkCannedPotato");
  table.insert(SuburbsDistributions["generalstorestorage"]["other"].items, 1);
  table.insert(SuburbsDistributions["generalstorestorage"]["other"].items, "GidOrganizedFood.OS6pkCannedTomato");
  table.insert(SuburbsDistributions["generalstorestorage"]["other"].items, 1);
  table.insert(SuburbsDistributions["generalstorestorage"]["other"].items, "GidOrganizedFood.OS8pkCannedTuna");
  table.insert(SuburbsDistributions["generalstorestorage"]["other"].items, 1);
  table.insert(SuburbsDistributions["generalstorestorage"]["other"].items, "GidOrganizedFood.OS4pkSardines");
  table.insert(SuburbsDistributions["generalstorestorage"]["other"].items, 1);
  table.insert(SuburbsDistributions["generalstorestorage"]["other"].items, "GidOrganizedFood.OS4pkCoffee");
  table.insert(SuburbsDistributions["generalstorestorage"]["other"].items, 0.5);
  table.insert(SuburbsDistributions["generalstorestorage"]["other"].items, "GidOrganizedFood.OS24pkWaterBottleFull");
  table.insert(SuburbsDistributions["generalstorestorage"]["other"].items, 1);
  table.insert(SuburbsDistributions["generalstorestorage"]["other"].items, "GidOrganizedFood.OS8pkCannedTuna");
  table.insert(SuburbsDistributions["generalstorestorage"]["other"].items, 1);
  table.insert(SuburbsDistributions["generalstorestorage"]["other"].items, "GidOrganizedFood.OS6pkPopDiet");
  table.insert(SuburbsDistributions["generalstorestorage"]["other"].items, 0.6);
  table.insert(SuburbsDistributions["generalstorestorage"]["other"].items, "GidOrganizedFood.OS6pkPop");
  table.insert(SuburbsDistributions["generalstorestorage"]["other"].items, 0.6);
  table.insert(SuburbsDistributions["generalstorestorage"]["other"].items, "GidOrganizedFood.OS6pkFizz");
  table.insert(SuburbsDistributions["generalstorestorage"]["other"].items, 0.6);
  table.insert(SuburbsDistributions["generalstore"]["other"].items, "GidOrganizedFood.OS6pkCannedSoup");
  table.insert(SuburbsDistributions["generalstore"]["other"].items, 1);
  table.insert(SuburbsDistributions["generalstore"]["other"].items, "GidOrganizedFood.OS6pkCannedBeans");
  table.insert(SuburbsDistributions["generalstore"]["other"].items, 1);
  table.insert(SuburbsDistributions["generalstore"]["other"].items, "GidOrganizedFood.OS6pkCannedBolognese");
  table.insert(SuburbsDistributions["generalstore"]["other"].items, 1);
  table.insert(SuburbsDistributions["generalstore"]["other"].items, "GidOrganizedFood.OS6pkCannedCarrots");
  table.insert(SuburbsDistributions["generalstore"]["other"].items, 1);
  table.insert(SuburbsDistributions["generalstore"]["other"].items, "GidOrganizedFood.OS6pkCannedChili");
  table.insert(SuburbsDistributions["generalstore"]["other"].items, 1);
  table.insert(SuburbsDistributions["generalstore"]["other"].items, "GidOrganizedFood.OS6pkCannedCorn");
  table.insert(SuburbsDistributions["generalstore"]["other"].items, 1);
  table.insert(SuburbsDistributions["generalstore"]["other"].items, "GidOrganizedFood.OS6pkCannedCornedBeef");
  table.insert(SuburbsDistributions["generalstore"]["other"].items, 1);
  table.insert(SuburbsDistributions["generalstore"]["other"].items, "GidOrganizedFood.OS6pkCannedMushSoup");
  table.insert(SuburbsDistributions["generalstore"]["other"].items, 1);
  table.insert(SuburbsDistributions["generalstore"]["other"].items, "GidOrganizedFood.OS6pkCannedPeas");
  table.insert(SuburbsDistributions["generalstore"]["other"].items, 1);
  table.insert(SuburbsDistributions["generalstore"]["other"].items, "GidOrganizedFood.OS6pkCannedPotato");
  table.insert(SuburbsDistributions["generalstore"]["other"].items, 1);
  table.insert(SuburbsDistributions["generalstore"]["other"].items, "GidOrganizedFood.OS6pkCannedTomato");
  table.insert(SuburbsDistributions["generalstore"]["other"].items, 1);
  table.insert(SuburbsDistributions["generalstore"]["other"].items, "GidOrganizedFood.OS8pkCannedTuna");
  table.insert(SuburbsDistributions["generalstore"]["other"].items, 1);
  table.insert(SuburbsDistributions["generalstore"]["other"].items, "GidOrganizedFood.OS4pkSardines");
  table.insert(SuburbsDistributions["generalstore"]["other"].items, 1);
  table.insert(SuburbsDistributions["generalstore"]["other"].items, "GidOrganizedFood.OS4pkCoffee");
  table.insert(SuburbsDistributions["generalstore"]["other"].items, 0.5);
  table.insert(SuburbsDistributions["generalstore"]["other"].items, "GidOrganizedFood.OS24pkWaterBottleFull");
  table.insert(SuburbsDistributions["generalstore"]["other"].items, 1);
  table.insert(SuburbsDistributions["generalstore"]["other"].items, "GidOrganizedFood.OS8pkCannedTuna");
  table.insert(SuburbsDistributions["generalstore"]["other"].items, 1);
  table.insert(SuburbsDistributions["generalstore"]["other"].items, "GidOrganizedFood.OS6pkPopDiet");
  table.insert(SuburbsDistributions["generalstore"]["other"].items, 0.6);
  table.insert(SuburbsDistributions["generalstore"]["other"].items, "GidOrganizedFood.OS6pkPop");
  table.insert(SuburbsDistributions["generalstore"]["other"].items, 0.6);
  table.insert(SuburbsDistributions["generalstore"]["other"].items, "GidOrganizedFood.OS6pkFizz");
  table.insert(SuburbsDistributions["generalstore"]["other"].items, 0.6);
  table.insert(SuburbsDistributions["grocery"]["counter"].items, "GidOrganizedFood.OS6pkCannedSoup");
  table.insert(SuburbsDistributions["grocery"]["counter"].items, 1);
  table.insert(SuburbsDistributions["grocery"]["counter"].items, "GidOrganizedFood.OS6pkCannedBeans");
  table.insert(SuburbsDistributions["grocery"]["counter"].items, 1);
  table.insert(SuburbsDistributions["grocery"]["counter"].items, "GidOrganizedFood.OS6pkCannedBolognese");
  table.insert(SuburbsDistributions["grocery"]["counter"].items, 1);
  table.insert(SuburbsDistributions["grocery"]["counter"].items, "GidOrganizedFood.OS6pkCannedCarrots");
  table.insert(SuburbsDistributions["grocery"]["counter"].items, 1);
  table.insert(SuburbsDistributions["grocery"]["counter"].items, "GidOrganizedFood.OS6pkCannedChili");
  table.insert(SuburbsDistributions["grocery"]["counter"].items, 1);
  table.insert(SuburbsDistributions["grocery"]["counter"].items, "GidOrganizedFood.OS6pkCannedCorn");
  table.insert(SuburbsDistributions["grocery"]["counter"].items, 1);
  table.insert(SuburbsDistributions["grocery"]["counter"].items, "GidOrganizedFood.OS6pkCannedCornedBeef");
  table.insert(SuburbsDistributions["grocery"]["counter"].items, 1);
  table.insert(SuburbsDistributions["grocery"]["counter"].items, "GidOrganizedFood.OS6pkCannedMushSoup");
  table.insert(SuburbsDistributions["grocery"]["counter"].items, 1);
  table.insert(SuburbsDistributions["grocery"]["counter"].items, "GidOrganizedFood.OS6pkCannedPeas");
  table.insert(SuburbsDistributions["grocery"]["counter"].items, 1);
  table.insert(SuburbsDistributions["grocery"]["counter"].items, "GidOrganizedFood.OS6pkCannedPotato");
  table.insert(SuburbsDistributions["grocery"]["counter"].items, 1);
  table.insert(SuburbsDistributions["grocery"]["counter"].items, "GidOrganizedFood.OS6pkCannedTomato");
  table.insert(SuburbsDistributions["grocery"]["counter"].items, 1);
  table.insert(SuburbsDistributions["grocery"]["counter"].items, "GidOrganizedFood.OS8pkCannedTuna");
  table.insert(SuburbsDistributions["grocery"]["counter"].items, 1);
  table.insert(SuburbsDistributions["grocery"]["counter"].items, "GidOrganizedFood.OS4pkSardines");
  table.insert(SuburbsDistributions["grocery"]["counter"].items, 1);
  table.insert(SuburbsDistributions["grocery"]["counter"].items, "GidOrganizedFood.OS4pkCoffee");
  table.insert(SuburbsDistributions["grocery"]["counter"].items, 0.5);
  table.insert(SuburbsDistributions["grocery"]["counter"].items, "GidOrganizedFood.OS24pkWaterBottleFull");
  table.insert(SuburbsDistributions["grocery"]["counter"].items, 1);
  table.insert(SuburbsDistributions["grocery"]["counter"].items, "GidOrganizedFood.OS8pkCannedTuna");
  table.insert(SuburbsDistributions["grocery"]["counter"].items, 1);
  table.insert(SuburbsDistributions["grocery"]["counter"].items, "GidOrganizedFood.OS6pkPopDiet");
  table.insert(SuburbsDistributions["grocery"]["counter"].items, 0.6);
  table.insert(SuburbsDistributions["grocery"]["counter"].items, "GidOrganizedFood.OS6pkPop");
  table.insert(SuburbsDistributions["grocery"]["counter"].items, 0.6);
  table.insert(SuburbsDistributions["grocery"]["counter"].items, "GidOrganizedFood.OS6pkFizz");
  table.insert(SuburbsDistributions["grocery"]["counter"].items, 0.6);
end

if string.match(getCore():getVersionNumber(), "41")
  then stockIWBUMS();
  else stockClassic();
end;
