require 'Items/Distributions'
require 'Items/ProceduralDistributions'

SuburbsDistributions = SuburbsDistributions or {}
ProceduralDistributions = ProceduralDistributions or {}

-- Medical Packs

table.insert(SuburbsDistributions["medicalstorage"]["counter"].items, "GidOrganized.OS12pkAdhesiveBandages");
table.insert(SuburbsDistributions["medicalstorage"]["counter"].items, 1);
table.insert(SuburbsDistributions["medicalstorage"]["counter"].items, "GidOrganized.OS9pkBandages");
table.insert(SuburbsDistributions["medicalstorage"]["counter"].items, 1);
table.insert(SuburbsDistributions["medicalstorage"]["counter"].items, "GidOrganized.OS9pkSterileBandages");
table.insert(SuburbsDistributions["medicalstorage"]["counter"].items, 1);
table.insert(SuburbsDistributions["medicalstorage"]["counter"].items, "GidOrganized.OS12pkCottonBalls");
table.insert(SuburbsDistributions["medicalstorage"]["counter"].items, 1);
table.insert(SuburbsDistributions["medicalstorage"]["counter"].items, "GidOrganized.OS50pkPainkillers");
table.insert(SuburbsDistributions["medicalstorage"]["counter"].items, 0.5);
table.insert(SuburbsDistributions["medicalstorage"]["counter"].items, "GidOrganized.OS50pkVitamins");
table.insert(SuburbsDistributions["medicalstorage"]["counter"].items, 0.5);
table.insert(SuburbsDistributions["medicalstorage"]["counter"].items, "GidOrganized.OS50pkBetaBlockers");
table.insert(SuburbsDistributions["medicalstorage"]["counter"].items, 0.5);
table.insert(SuburbsDistributions["medicalstorage"]["counter"].items, "GidOrganized.OS50pkAntidepressants");
table.insert(SuburbsDistributions["medicalstorage"]["counter"].items, 0.5);
table.insert(SuburbsDistributions["medicalstorage"]["counter"].items, "GidOrganized.OS50pkSleepingPills");
table.insert(SuburbsDistributions["medicalstorage"]["counter"].items, 0.5);
table.insert(SuburbsDistributions["medicalstorage"]["counter"].items, "GidOrganized.OS4pkDisinfectant");
table.insert(SuburbsDistributions["medicalstorage"]["counter"].items, 1);
table.insert(SuburbsDistributions["medicalstorage"]["counter"].items, "GidOrganized.OS30pkAlcoholWipes");
table.insert(SuburbsDistributions["medicalstorage"]["counter"].items, 0.8);
table.insert(SuburbsDistributions["medicalstorage"]["counter"].items, "GidOrganized.OS30pkAntibiotics");
table.insert(SuburbsDistributions["medicalstorage"]["counter"].items, 0.2);

table.insert(SuburbsDistributions["medicalstorage"]["metal_shelves"].items, "GidOrganized.OS12pkAdhesiveBandages");
table.insert(SuburbsDistributions["medicalstorage"]["metal_shelves"].items, 1);
table.insert(SuburbsDistributions["medicalstorage"]["metal_shelves"].items, "GidOrganized.OS9pkBandages");
table.insert(SuburbsDistributions["medicalstorage"]["metal_shelves"].items, 1);
table.insert(SuburbsDistributions["medicalstorage"]["metal_shelves"].items, "GidOrganized.OS9pkSterileBandages");
table.insert(SuburbsDistributions["medicalstorage"]["metal_shelves"].items, 1);
table.insert(SuburbsDistributions["medicalstorage"]["metal_shelves"].items, "GidOrganized.OS12pkCottonBalls");
table.insert(SuburbsDistributions["medicalstorage"]["metal_shelves"].items, 1);
table.insert(SuburbsDistributions["medicalstorage"]["metal_shelves"].items, "GidOrganized.OS50pkPainkillers");
table.insert(SuburbsDistributions["medicalstorage"]["metal_shelves"].items, 0.5);
table.insert(SuburbsDistributions["medicalstorage"]["metal_shelves"].items, "GidOrganized.OS50pkVitamins");
table.insert(SuburbsDistributions["medicalstorage"]["metal_shelves"].items, 0.5);
table.insert(SuburbsDistributions["medicalstorage"]["metal_shelves"].items, "GidOrganized.OS50pkBetaBlockers");
table.insert(SuburbsDistributions["medicalstorage"]["metal_shelves"].items, 0.5);
table.insert(SuburbsDistributions["medicalstorage"]["metal_shelves"].items, "GidOrganized.OS50pkAntidepressants");
table.insert(SuburbsDistributions["medicalstorage"]["metal_shelves"].items, 0.5);
table.insert(SuburbsDistributions["medicalstorage"]["metal_shelves"].items, "GidOrganized.OS50pkSleepingPills");
table.insert(SuburbsDistributions["medicalstorage"]["metal_shelves"].items, 0.5);
table.insert(SuburbsDistributions["medicalstorage"]["metal_shelves"].items, "GidOrganized.OS4pkDisinfectant");
table.insert(SuburbsDistributions["medicalstorage"]["metal_shelves"].items, 1);
table.insert(SuburbsDistributions["medicalstorage"]["metal_shelves"].items, "GidOrganized.OS30pkAlcoholWipes");
table.insert(SuburbsDistributions["medicalstorage"]["metal_shelves"].items, 0.8);
table.insert(SuburbsDistributions["medicalstorage"]["metal_shelves"].items, "GidOrganized.OS30pkAntibiotics");
table.insert(SuburbsDistributions["medicalstorage"]["metal_shelves"].items, 0.2);

table.insert(SuburbsDistributions["pharmacystorage"]["counter"].items, "GidOrganized.OS12pkAdhesiveBandages");
table.insert(SuburbsDistributions["pharmacystorage"]["counter"].items, 1);
table.insert(SuburbsDistributions["pharmacystorage"]["counter"].items, "GidOrganized.OS9pkBandages");
table.insert(SuburbsDistributions["pharmacystorage"]["counter"].items, 1);
table.insert(SuburbsDistributions["pharmacystorage"]["counter"].items, "GidOrganized.OS9pkSterileBandages");
table.insert(SuburbsDistributions["pharmacystorage"]["counter"].items, 1);
table.insert(SuburbsDistributions["pharmacystorage"]["counter"].items, "GidOrganized.OS12pkCottonBcounters");
table.insert(SuburbsDistributions["pharmacystorage"]["counter"].items, 1);
table.insert(SuburbsDistributions["pharmacystorage"]["counter"].items, "GidOrganized.OS50pkPainkillers");
table.insert(SuburbsDistributions["pharmacystorage"]["counter"].items, 0.5);
table.insert(SuburbsDistributions["pharmacystorage"]["counter"].items, "GidOrganized.OS50pkVitamins");
table.insert(SuburbsDistributions["pharmacystorage"]["counter"].items, 0.5);
table.insert(SuburbsDistributions["pharmacystorage"]["counter"].items, "GidOrganized.OS50pkBetaBlockers");
table.insert(SuburbsDistributions["pharmacystorage"]["counter"].items, 0.5);
table.insert(SuburbsDistributions["pharmacystorage"]["counter"].items, "GidOrganized.OS50pkAntidepressants");
table.insert(SuburbsDistributions["pharmacystorage"]["counter"].items, 0.5);
table.insert(SuburbsDistributions["pharmacystorage"]["counter"].items, "GidOrganized.OS50pkSleepingPills");
table.insert(SuburbsDistributions["pharmacystorage"]["counter"].items, 0.5);
table.insert(SuburbsDistributions["pharmacystorage"]["counter"].items, "GidOrganized.OS4pkDisinfectant");
table.insert(SuburbsDistributions["pharmacystorage"]["counter"].items, 1);
table.insert(SuburbsDistributions["pharmacystorage"]["counter"].items, "GidOrganized.OS30pkAlcoholWipes");
table.insert(SuburbsDistributions["pharmacystorage"]["counter"].items, 0.8);
table.insert(SuburbsDistributions["pharmacystorage"]["counter"].items, "GidOrganized.OS30pkAntibiotics");
table.insert(SuburbsDistributions["pharmacystorage"]["counter"].items, 0.2);

table.insert(SuburbsDistributions["medicaloffice"]["counter"].items, "GidOrganized.OS12pkAdhesiveBandages");
table.insert(SuburbsDistributions["medicaloffice"]["counter"].items, 1);
table.insert(SuburbsDistributions["medicaloffice"]["counter"].items, "GidOrganized.OS9pkBandages");
table.insert(SuburbsDistributions["medicaloffice"]["counter"].items, 1);
table.insert(SuburbsDistributions["medicaloffice"]["counter"].items, "GidOrganized.OS9pkSterileBandages");
table.insert(SuburbsDistributions["medicaloffice"]["counter"].items, 1);
table.insert(SuburbsDistributions["medicaloffice"]["counter"].items, "GidOrganized.OS12pkCottonBcounters");
table.insert(SuburbsDistributions["medicaloffice"]["counter"].items, 1);
table.insert(SuburbsDistributions["medicaloffice"]["counter"].items, "GidOrganized.OS50pkPainkillers");
table.insert(SuburbsDistributions["medicaloffice"]["counter"].items, 0.5);
table.insert(SuburbsDistributions["medicaloffice"]["counter"].items, "GidOrganized.OS50pkVitamins");
table.insert(SuburbsDistributions["medicaloffice"]["counter"].items, 0.5);
table.insert(SuburbsDistributions["medicaloffice"]["counter"].items, "GidOrganized.OS50pkBetaBlockers");
table.insert(SuburbsDistributions["medicaloffice"]["counter"].items, 0.5);
table.insert(SuburbsDistributions["medicaloffice"]["counter"].items, "GidOrganized.OS50pkAntidepressants");
table.insert(SuburbsDistributions["medicaloffice"]["counter"].items, 0.5);
table.insert(SuburbsDistributions["medicaloffice"]["counter"].items, "GidOrganized.OS50pkSleepingPills");
table.insert(SuburbsDistributions["medicaloffice"]["counter"].items, 0.5);
table.insert(SuburbsDistributions["medicaloffice"]["counter"].items, "GidOrganized.OS4pkDisinfectant");
table.insert(SuburbsDistributions["medicaloffice"]["counter"].items, 1);
table.insert(SuburbsDistributions["medicaloffice"]["counter"].items, "GidOrganized.OS30pkAlcoholWipes");
table.insert(SuburbsDistributions["medicaloffice"]["counter"].items, 0.8);
table.insert(SuburbsDistributions["medicaloffice"]["counter"].items, "GidOrganized.OS30pkAntibiotics");
table.insert(SuburbsDistributions["medicaloffice"]["counter"].items, 0.2);

-- DuckTape

table.insert(SuburbsDistributions["shed"]["other"].items, "GidOrganizedFood.OS4pkDuctTape");
table.insert(SuburbsDistributions["shed"]["other"].items, 1);

-- table.insert(SuburbsDistributions["garagestorage"]["crate"].items, "GidOrganizedFood.OS4pkDuctTape");
-- table.insert(SuburbsDistributions["garagestorage"]["crate"].items, 1);
-- table.insert(SuburbsDistributions["garagestorage"]["other"].items, "GidOrganizedFood.OS4pkDuctTape");
-- table.insert(SuburbsDistributions["garagestorage"]["other"].items, 1);

table.insert(SuburbsDistributions["toolstore"]["shelves"].items, "GidOrganizedFood.OS4pkDuctTape");
table.insert(SuburbsDistributions["toolstore"]["shelves"].items, 1);
table.insert(SuburbsDistributions["toolstore"]["counter"].items, "GidOrganizedFood.OS4pkDuctTape");
table.insert(SuburbsDistributions["toolstore"]["counter"].items, 1);

-- Food Packs

table.insert(SuburbsDistributions["generalstorestorage"]["other"].items, "GidOrganizedFood.OS6pkCannedSoup");
table.insert(SuburbsDistributions["generalstorestorage"]["other"].items, 1);
table.insert(SuburbsDistributions["generalstorestorage"]["other"].items, "GidOrganizedFood.OS6pkCannedBeans");
table.insert(SuburbsDistributions["generalstorestorage"]["other"].items, 1);
table.insert(SuburbsDistributions["generalstorestorage"]["other"].items, "GidOrganizedFood.OS6pkCannedBolognese");
table.insert(SuburbsDistributions["generalstorestorage"]["other"].items, 1);
table.insert(SuburbsDistributions["generalstorestorage"]["other"].items, "GidOrganizedFood.OS6pkCannedCarrots");
table.insert(SuburbsDistributions["generalstorestorage"]["other"].items, 1);
table.insert(SuburbsDistributions["generalstorestorage"]["other"].items, "GidOrganizedFood.OS6pkCannedChili");
table.insert(SuburbsDistributions["generalstorestorage"]["other"].items, 1);
table.insert(SuburbsDistributions["generalstorestorage"]["other"].items, "GidOrganizedFood.OS6pkCannedCorn");
table.insert(SuburbsDistributions["generalstorestorage"]["other"].items, 1);
table.insert(SuburbsDistributions["generalstorestorage"]["other"].items, "GidOrganizedFood.OS6pkCannedCornedBeef");
table.insert(SuburbsDistributions["generalstorestorage"]["other"].items, 1);
table.insert(SuburbsDistributions["generalstorestorage"]["other"].items, "GidOrganizedFood.OS6pkCannedMushSoup");
table.insert(SuburbsDistributions["generalstorestorage"]["other"].items, 1);
table.insert(SuburbsDistributions["generalstorestorage"]["other"].items, "GidOrganizedFood.OS6pkCannedPeas");
table.insert(SuburbsDistributions["generalstorestorage"]["other"].items, 1);
table.insert(SuburbsDistributions["generalstorestorage"]["other"].items, "GidOrganizedFood.OS6pkCannedPotato");
table.insert(SuburbsDistributions["generalstorestorage"]["other"].items, 1);
table.insert(SuburbsDistributions["generalstorestorage"]["other"].items, "GidOrganizedFood.OS6pkCannedTomato");
table.insert(SuburbsDistributions["generalstorestorage"]["other"].items, 1);
table.insert(SuburbsDistributions["generalstorestorage"]["other"].items, "GidOrganizedFood.OS8pkCannedTuna");
table.insert(SuburbsDistributions["generalstorestorage"]["other"].items, 1);
table.insert(SuburbsDistributions["generalstorestorage"]["other"].items, "GidOrganizedFood.OS4pkSardines");
table.insert(SuburbsDistributions["generalstorestorage"]["other"].items, 1);
table.insert(SuburbsDistributions["generalstorestorage"]["other"].items, "GidOrganizedFood.OS4pkCoffee");
table.insert(SuburbsDistributions["generalstorestorage"]["other"].items, 1);
table.insert(SuburbsDistributions["generalstorestorage"]["other"].items, "GidOrganizedFood.OS24pkWaterBottleFull");
table.insert(SuburbsDistributions["generalstorestorage"]["other"].items, 1);
table.insert(SuburbsDistributions["generalstorestorage"]["other"].items, "GidOrganizedFood.OS8pkCannedTuna");
table.insert(SuburbsDistributions["generalstorestorage"]["other"].items, 1);
table.insert(SuburbsDistributions["generalstorestorage"]["other"].items, "GidOrganizedFood.OS6pkPopDiet");
table.insert(SuburbsDistributions["generalstorestorage"]["other"].items, 0.6);
table.insert(SuburbsDistributions["generalstorestorage"]["other"].items, "GidOrganizedFood.OS6pkPop");
table.insert(SuburbsDistributions["generalstorestorage"]["other"].items, 0.6);
table.insert(SuburbsDistributions["generalstorestorage"]["other"].items, "GidOrganizedFood.OS6pkFizz");
table.insert(SuburbsDistributions["generalstorestorage"]["other"].items, 0.6);

table.insert(SuburbsDistributions["generalstore"]["other"].items, "GidOrganizedFood.OS6pkCannedSoup");
table.insert(SuburbsDistributions["generalstore"]["other"].items, 1);
table.insert(SuburbsDistributions["generalstore"]["other"].items, "GidOrganizedFood.OS6pkCannedBeans");
table.insert(SuburbsDistributions["generalstore"]["other"].items, 1);
table.insert(SuburbsDistributions["generalstore"]["other"].items, "GidOrganizedFood.OS6pkCannedBolognese");
table.insert(SuburbsDistributions["generalstore"]["other"].items, 1);
table.insert(SuburbsDistributions["generalstore"]["other"].items, "GidOrganizedFood.OS6pkCannedCarrots");
table.insert(SuburbsDistributions["generalstore"]["other"].items, 1);
table.insert(SuburbsDistributions["generalstore"]["other"].items, "GidOrganizedFood.OS6pkCannedChili");
table.insert(SuburbsDistributions["generalstore"]["other"].items, 1);
table.insert(SuburbsDistributions["generalstore"]["other"].items, "GidOrganizedFood.OS6pkCannedCorn");
table.insert(SuburbsDistributions["generalstore"]["other"].items, 1);
table.insert(SuburbsDistributions["generalstore"]["other"].items, "GidOrganizedFood.OS6pkCannedCornedBeef");
table.insert(SuburbsDistributions["generalstore"]["other"].items, 1);
table.insert(SuburbsDistributions["generalstore"]["other"].items, "GidOrganizedFood.OS6pkCannedMushSoup");
table.insert(SuburbsDistributions["generalstore"]["other"].items, 1);
table.insert(SuburbsDistributions["generalstore"]["other"].items, "GidOrganizedFood.OS6pkCannedPeas");
table.insert(SuburbsDistributions["generalstore"]["other"].items, 1);
table.insert(SuburbsDistributions["generalstore"]["other"].items, "GidOrganizedFood.OS6pkCannedPotato");
table.insert(SuburbsDistributions["generalstore"]["other"].items, 1);
table.insert(SuburbsDistributions["generalstore"]["other"].items, "GidOrganizedFood.OS6pkCannedTomato");
table.insert(SuburbsDistributions["generalstore"]["other"].items, 1);
table.insert(SuburbsDistributions["generalstore"]["other"].items, "GidOrganizedFood.OS8pkCannedTuna");
table.insert(SuburbsDistributions["generalstore"]["other"].items, 1);
table.insert(SuburbsDistributions["generalstore"]["other"].items, "GidOrganizedFood.OS4pkSardines");
table.insert(SuburbsDistributions["generalstore"]["other"].items, 1);
table.insert(SuburbsDistributions["generalstore"]["other"].items, "GidOrganizedFood.OS4pkCoffee");
table.insert(SuburbsDistributions["generalstore"]["other"].items, 1);
table.insert(SuburbsDistributions["generalstore"]["other"].items, "GidOrganizedFood.OS24pkWaterBottleFull");
table.insert(SuburbsDistributions["generalstore"]["other"].items, 1);
table.insert(SuburbsDistributions["generalstore"]["other"].items, "GidOrganizedFood.OS8pkCannedTuna");
table.insert(SuburbsDistributions["generalstore"]["other"].items, 1);
table.insert(SuburbsDistributions["generalstore"]["other"].items, "GidOrganizedFood.OS6pkPopDiet");
table.insert(SuburbsDistributions["generalstore"]["other"].items, 0.6);
table.insert(SuburbsDistributions["generalstore"]["other"].items, "GidOrganizedFood.OS6pkPop");
table.insert(SuburbsDistributions["generalstore"]["other"].items, 0.6);
table.insert(SuburbsDistributions["generalstore"]["other"].items, "GidOrganizedFood.OS6pkFizz");
table.insert(SuburbsDistributions["generalstore"]["other"].items, 0.6);

table.insert(SuburbsDistributions["grocery"]["counter"].items, "GidOrganizedFood.OS6pkCannedSoup");
table.insert(SuburbsDistributions["grocery"]["counter"].items, 1);
table.insert(SuburbsDistributions["grocery"]["counter"].items, "GidOrganizedFood.OS6pkCannedBeans");
table.insert(SuburbsDistributions["grocery"]["counter"].items, 1);
table.insert(SuburbsDistributions["grocery"]["counter"].items, "GidOrganizedFood.OS6pkCannedBolognese");
table.insert(SuburbsDistributions["grocery"]["counter"].items, 1);
table.insert(SuburbsDistributions["grocery"]["counter"].items, "GidOrganizedFood.OS6pkCannedCarrots");
table.insert(SuburbsDistributions["grocery"]["counter"].items, 1);
table.insert(SuburbsDistributions["grocery"]["counter"].items, "GidOrganizedFood.OS6pkCannedChili");
table.insert(SuburbsDistributions["grocery"]["counter"].items, 1);
table.insert(SuburbsDistributions["grocery"]["counter"].items, "GidOrganizedFood.OS6pkCannedCorn");
table.insert(SuburbsDistributions["grocery"]["counter"].items, 1);
table.insert(SuburbsDistributions["grocery"]["counter"].items, "GidOrganizedFood.OS6pkCannedCornedBeef");
table.insert(SuburbsDistributions["grocery"]["counter"].items, 1);
table.insert(SuburbsDistributions["grocery"]["counter"].items, "GidOrganizedFood.OS6pkCannedMushSoup");
table.insert(SuburbsDistributions["grocery"]["counter"].items, 1);
table.insert(SuburbsDistributions["grocery"]["counter"].items, "GidOrganizedFood.OS6pkCannedPeas");
table.insert(SuburbsDistributions["grocery"]["counter"].items, 1);
table.insert(SuburbsDistributions["grocery"]["counter"].items, "GidOrganizedFood.OS6pkCannedPotato");
table.insert(SuburbsDistributions["grocery"]["counter"].items, 1);
table.insert(SuburbsDistributions["grocery"]["counter"].items, "GidOrganizedFood.OS6pkCannedTomato");
table.insert(SuburbsDistributions["grocery"]["counter"].items, 1);
table.insert(SuburbsDistributions["grocery"]["counter"].items, "GidOrganizedFood.OS8pkCannedTuna");
table.insert(SuburbsDistributions["grocery"]["counter"].items, 1);
table.insert(SuburbsDistributions["grocery"]["counter"].items, "GidOrganizedFood.OS4pkSardines");
table.insert(SuburbsDistributions["grocery"]["counter"].items, 1);
table.insert(SuburbsDistributions["grocery"]["counter"].items, "GidOrganizedFood.OS4pkCoffee");
table.insert(SuburbsDistributions["grocery"]["counter"].items, 1);
table.insert(SuburbsDistributions["grocery"]["counter"].items, "GidOrganizedFood.OS24pkWaterBottleFull");
table.insert(SuburbsDistributions["grocery"]["counter"].items, 1);
table.insert(SuburbsDistributions["grocery"]["counter"].items, "GidOrganizedFood.OS8pkCannedTuna");
table.insert(SuburbsDistributions["grocery"]["counter"].items, 1);
table.insert(SuburbsDistributions["grocery"]["counter"].items, "GidOrganizedFood.OS6pkPopDiet");
table.insert(SuburbsDistributions["grocery"]["counter"].items, 0.6);
table.insert(SuburbsDistributions["grocery"]["counter"].items, "GidOrganizedFood.OS6pkPop");
table.insert(SuburbsDistributions["grocery"]["counter"].items, 0.6);
table.insert(SuburbsDistributions["grocery"]["counter"].items, "GidOrganizedFood.OS6pkFizz");
table.insert(SuburbsDistributions["grocery"]["counter"].items, 0.6);

-- table.insert(SuburbsDistributions["grocerystorage"]["other"].items, "GidOrganizedFood.OS6pkCannedSoup");
-- table.insert(SuburbsDistributions["grocerystorage"]["other"].items, 1);
-- table.insert(SuburbsDistributions["grocerystorage"]["other"].items, "GidOrganizedFood.OS6pkCannedBeans");
-- table.insert(SuburbsDistributions["grocerystorage"]["other"].items, 1);
-- table.insert(SuburbsDistributions["grocerystorage"]["other"].items, "GidOrganizedFood.OS6pkCannedBolognese");
-- table.insert(SuburbsDistributions["grocerystorage"]["other"].items, 1);
-- table.insert(SuburbsDistributions["grocerystorage"]["other"].items, "GidOrganizedFood.OS6pkCannedCarrots");
-- table.insert(SuburbsDistributions["grocerystorage"]["other"].items, 1);
-- table.insert(SuburbsDistributions["grocerystorage"]["other"].items, "GidOrganizedFood.OS6pkCannedChili");
-- table.insert(SuburbsDistributions["grocerystorage"]["other"].items, 1);
-- table.insert(SuburbsDistributions["grocerystorage"]["other"].items, "GidOrganizedFood.OS6pkCannedCorn");
-- table.insert(SuburbsDistributions["grocerystorage"]["other"].items, 1);
-- table.insert(SuburbsDistributions["grocerystorage"]["other"].items, "GidOrganizedFood.OS6pkCannedCornedBeef");
-- table.insert(SuburbsDistributions["grocerystorage"]["other"].items, 1);
-- table.insert(SuburbsDistributions["grocerystorage"]["other"].items, "GidOrganizedFood.OS6pkCannedMushSoup");
-- table.insert(SuburbsDistributions["grocerystorage"]["other"].items, 1);
-- table.insert(SuburbsDistributions["grocerystorage"]["other"].items, "GidOrganizedFood.OS6pkCannedPeas");
-- table.insert(SuburbsDistributions["grocerystorage"]["other"].items, 1);
-- table.insert(SuburbsDistributions["grocerystorage"]["other"].items, "GidOrganizedFood.OS6pkCannedPotato");
-- table.insert(SuburbsDistributions["grocerystorage"]["other"].items, 1);
-- table.insert(SuburbsDistributions["grocerystorage"]["other"].items, "GidOrganizedFood.OS6pkCannedTomato");
-- table.insert(SuburbsDistributions["grocerystorage"]["other"].items, 1);
-- table.insert(SuburbsDistributions["grocerystorage"]["other"].items, "GidOrganizedFood.OS8pkCannedTuna");
-- table.insert(SuburbsDistributions["grocerystorage"]["other"].items, 1);
-- table.insert(SuburbsDistributions["grocerystorage"]["other"].items, "GidOrganizedFood.OS4pkSardines");
-- table.insert(SuburbsDistributions["grocerystorage"]["other"].items, 1);
-- table.insert(SuburbsDistributions["grocerystorage"]["other"].items, "GidOrganizedFood.OS4pkCoffee");
-- table.insert(SuburbsDistributions["grocerystorage"]["other"].items, 1);
-- table.insert(SuburbsDistributions["grocerystorage"]["other"].items, "GidOrganizedFood.OS24pkWaterBottleFull");
-- table.insert(SuburbsDistributions["grocerystorage"]["other"].items, 1);
-- table.insert(SuburbsDistributions["grocerystorage"]["other"].items, "GidOrganizedFood.OS8pkCannedTuna");
-- table.insert(SuburbsDistributions["grocerystorage"]["other"].items, 1);
-- table.insert(SuburbsDistributions["grocerystorage"]["other"].items, "GidOrganizedFood.OS6pkPopDiet");
-- table.insert(SuburbsDistributions["grocerystorage"]["other"].items, 0.6);
-- table.insert(SuburbsDistributions["grocerystorage"]["other"].items, "GidOrganizedFood.OS6pkPop");
-- table.insert(SuburbsDistributions["grocerystorage"]["other"].items, 0.6);
-- table.insert(SuburbsDistributions["grocerystorage"]["other"].items, "GidOrganizedFood.OS6pkFizz");
-- table.insert(SuburbsDistributions["grocerystorage"]["other"].items, 0.6);

-- houses

table.insert(SuburbsDistributions["kitchen"]["counter"].items, "GidOrganizedFood.OS6pkCannedSoup");
table.insert(SuburbsDistributions["kitchen"]["counter"].items, 0.5);
table.insert(SuburbsDistributions["kitchen"]["counter"].items, "GidOrganizedFood.OS6pkCannedBeans");
table.insert(SuburbsDistributions["kitchen"]["counter"].items, 0.5);
table.insert(SuburbsDistributions["kitchen"]["counter"].items, "GidOrganizedFood.OS6pkCannedBolognese");
table.insert(SuburbsDistributions["kitchen"]["counter"].items, 0.5);
table.insert(SuburbsDistributions["kitchen"]["counter"].items, "GidOrganizedFood.OS6pkCannedCarrots");
table.insert(SuburbsDistributions["kitchen"]["counter"].items, 0.5);
table.insert(SuburbsDistributions["kitchen"]["counter"].items, "GidOrganizedFood.OS6pkCannedChili");
table.insert(SuburbsDistributions["kitchen"]["counter"].items, 0.5);
table.insert(SuburbsDistributions["kitchen"]["counter"].items, "GidOrganizedFood.OS6pkCannedCorn");
table.insert(SuburbsDistributions["kitchen"]["counter"].items, 0.5);
table.insert(SuburbsDistributions["kitchen"]["counter"].items, "GidOrganizedFood.OS6pkCannedCornedBeef");
table.insert(SuburbsDistributions["kitchen"]["counter"].items, 0.5);
table.insert(SuburbsDistributions["kitchen"]["counter"].items, "GidOrganizedFood.OS6pkCannedMushSoup");
table.insert(SuburbsDistributions["kitchen"]["counter"].items, 0.5);
table.insert(SuburbsDistributions["kitchen"]["counter"].items, "GidOrganizedFood.OS6pkCannedPeas");
table.insert(SuburbsDistributions["kitchen"]["counter"].items, 0.5);
table.insert(SuburbsDistributions["kitchen"]["counter"].items, "GidOrganizedFood.OS6pkCannedPotato");
table.insert(SuburbsDistributions["kitchen"]["counter"].items, 0.5);
table.insert(SuburbsDistributions["kitchen"]["counter"].items, "GidOrganizedFood.OS6pkCannedTomato");
table.insert(SuburbsDistributions["kitchen"]["counter"].items, 0.5);
table.insert(SuburbsDistributions["kitchen"]["counter"].items, "GidOrganizedFood.OS8pkCannedTuna");
table.insert(SuburbsDistributions["kitchen"]["counter"].items, 0.5);
table.insert(SuburbsDistributions["kitchen"]["counter"].items, "GidOrganizedFood.OS4pkSardines");
table.insert(SuburbsDistributions["kitchen"]["counter"].items, 0.5);
table.insert(SuburbsDistributions["kitchen"]["counter"].items, "GidOrganizedFood.OS4pkCoffee");
table.insert(SuburbsDistributions["kitchen"]["counter"].items, 0.5);
table.insert(SuburbsDistributions["kitchen"]["counter"].items, "GidOrganizedFood.OS24pkWaterBottleFull");
table.insert(SuburbsDistributions["kitchen"]["counter"].items, 0.5);
table.insert(SuburbsDistributions["kitchen"]["counter"].items, "GidOrganizedFood.OS8pkCannedTuna");
table.insert(SuburbsDistributions["kitchen"]["counter"].items, 0.5);
table.insert(SuburbsDistributions["kitchen"]["counter"].items, "GidOrganizedFood.OS6pkPopDiet");
table.insert(SuburbsDistributions["kitchen"]["counter"].items, 0.3);
table.insert(SuburbsDistributions["kitchen"]["counter"].items, "GidOrganizedFood.OS6pkPop");
table.insert(SuburbsDistributions["kitchen"]["counter"].items, 0.3);
table.insert(SuburbsDistributions["kitchen"]["counter"].items, "GidOrganizedFood.OS6pkFizz");
table.insert(SuburbsDistributions["kitchen"]["counter"].items, 0.3);
